"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _github_conteo from './github-conteo.bones.json'

registerBones({
  "github-conteo": _github_conteo,
})
