// AUTO-GENERADO por scripts/gen-icon-variants.ts — NO EDITAR A MANO, se pierde en el siguiente
// `npm run gen:variants`. Fuente: Object.keys(animations) del registro compuesto (curado +
// generado), no de lucide-static — regenerar tras cualquier cambio de coreografía en
// curated-icons.ts, no solo tras un bump de Lucide.
//
// Las variantes de animación que trae cada icono, sin arrastrar su geometría: quien solo necesita
// saber QUÉ hay para elegir no debería pagar el catálogo completo por preguntarlo.

export const ICON_VARIANTS: Record<string, readonly string[]> = {
  'a-arrow-down': ['draw', 'default', 'assemble', 'reveal'],
  'a-arrow-up': ['draw', 'default', 'assemble', 'reveal'],
  'a-large-small': ['draw', 'default', 'reveal'],
  accessibility: ['draw', 'default', 'hold', 'idle', 'reveal'],
  activity: ['draw', 'default', 'reveal'],
  ad: ['draw', 'default', 'hold', 'reveal'],
  'air-vent': ['draw', 'default', 'hold', 'reveal'],
  airplay: ['draw', 'default', 'reveal'],
  'alarm-clock': ['draw', 'default', 'alert', 'reveal'],
  'alarm-clock-check': ['draw', 'default', 'ring', 'mark', 'reveal'],
  'alarm-clock-minus': ['draw', 'default', 'ring', 'reveal'],
  'alarm-clock-off': ['draw', 'default', 'alert', 'strike', 'reveal'],
  'alarm-clock-plus': ['draw', 'default', 'ring', 'reveal'],
  'alarm-smoke': ['draw', 'default', 'reveal'],
  album: ['draw', 'default', 'hold', 'reveal'],
  'align-center-horizontal': ['draw', 'default', 'nudge', 'reveal'],
  'align-center-vertical': ['draw', 'default', 'nudge', 'reveal'],
  'align-end-horizontal': ['draw', 'default', 'nudge', 'reveal'],
  'align-end-vertical': ['draw', 'default', 'nudge', 'reveal'],
  'align-horizontal-distribute-center': ['draw', 'default', 'nudge', 'reveal'],
  'align-horizontal-distribute-end': ['draw', 'default', 'nudge', 'reveal'],
  'align-horizontal-distribute-start': ['draw', 'default', 'nudge', 'reveal'],
  'align-horizontal-justify-center': ['draw', 'default', 'nudge', 'reveal'],
  'align-horizontal-justify-end': ['draw', 'default', 'nudge', 'reveal'],
  'align-horizontal-justify-start': ['draw', 'default', 'nudge', 'reveal'],
  'align-horizontal-space-around': ['draw', 'default', 'nudge', 'reveal'],
  'align-horizontal-space-between': ['draw', 'default', 'nudge', 'reveal'],
  'align-start-horizontal': ['draw', 'default', 'nudge', 'reveal'],
  'align-start-vertical': ['draw', 'default', 'nudge', 'reveal'],
  'align-vertical-distribute-center': ['draw', 'default', 'nudge', 'reveal'],
  'align-vertical-distribute-end': ['draw', 'default', 'nudge', 'reveal'],
  'align-vertical-distribute-start': ['draw', 'default', 'nudge', 'reveal'],
  'align-vertical-justify-center': ['draw', 'default', 'nudge', 'reveal'],
  'align-vertical-justify-end': ['draw', 'default', 'nudge', 'reveal'],
  'align-vertical-justify-start': ['draw', 'default', 'nudge', 'reveal'],
  'align-vertical-space-around': ['draw', 'default', 'nudge', 'reveal'],
  'align-vertical-space-between': ['draw', 'default', 'nudge', 'reveal'],
  ambulance: ['draw', 'default', 'hold', 'reveal'],
  ampersand: ['draw', 'default', 'reveal'],
  ampersands: ['draw', 'default', 'reveal'],
  amphora: ['draw', 'default', 'hold', 'reveal'],
  anchor: ['draw', 'default', 'hold', 'reveal'],
  angle: ['draw', 'default', 'hold', 'reveal'],
  antenna: ['draw', 'default', 'hold', 'reveal'],
  anvil: ['draw', 'default', 'reveal'],
  aperture: ['draw', 'default', 'hold', 'reveal'],
  'app-window': ['draw', 'default', 'reveal'],
  'app-window-mac': ['draw', 'default', 'reveal'],
  apple: ['draw', 'default', 'hold', 'reveal'],
  archive: ['draw', 'default', 'reveal'],
  'archive-restore': ['draw', 'default', 'reveal'],
  'archive-x': ['draw', 'default', 'reveal'],
  armchair: ['draw', 'default', 'hold', 'reveal'],
  'arrow-big-down': ['draw', 'default', 'reveal'],
  'arrow-big-down-dash': ['draw', 'default', 'reveal'],
  'arrow-big-left': ['draw', 'default', 'reveal'],
  'arrow-big-left-dash': ['draw', 'default', 'reveal'],
  'arrow-big-right': ['draw', 'default', 'reveal'],
  'arrow-big-right-dash': ['draw', 'default', 'reveal'],
  'arrow-big-up': ['draw', 'default', 'reveal'],
  'arrow-big-up-dash': ['draw', 'default', 'reveal'],
  'arrow-down': ['draw', 'default', 'active', 'nudge', 'reveal'],
  'arrow-down-0-1': ['draw', 'default', 'reveal'],
  'arrow-down-1-0': ['draw', 'default', 'reveal'],
  'arrow-down-a-z': ['draw', 'default', 'reveal'],
  'arrow-down-from-line': ['draw', 'default', 'reveal'],
  'arrow-down-left': ['draw', 'default', 'active', 'nudge', 'reveal'],
  'arrow-down-narrow-wide': ['draw', 'default', 'flip', 'reveal'],
  'arrow-down-right': ['draw', 'default', 'active', 'nudge', 'reveal'],
  'arrow-down-to-dot': ['draw', 'default', 'reveal'],
  'arrow-down-to-line': ['draw', 'default', 'reveal'],
  'arrow-down-up': ['draw', 'default', 'nudge', 'flip', 'reveal'],
  'arrow-down-wide-narrow': ['draw', 'default', 'flip', 'reveal'],
  'arrow-down-z-a': ['draw', 'default', 'reveal'],
  'arrow-left': ['draw', 'default', 'active', 'nudge', 'reveal'],
  'arrow-left-from-line': ['draw', 'default', 'reveal'],
  'arrow-left-right': ['draw', 'default', 'nudge', 'flip', 'reveal'],
  'arrow-left-to-line': ['draw', 'default', 'reveal'],
  'arrow-right': ['draw', 'default', 'active', 'nudge', 'reveal'],
  'arrow-right-from-line': ['draw', 'default', 'reveal'],
  'arrow-right-left': ['draw', 'default', 'flip', 'reveal'],
  'arrow-right-to-line': ['draw', 'default', 'reveal'],
  'arrow-up': ['draw', 'default', 'active', 'nudge', 'reveal'],
  'arrow-up-0-1': ['draw', 'default', 'assemble', 'reveal'],
  'arrow-up-1-0': ['draw', 'default', 'assemble', 'reveal'],
  'arrow-up-a-z': ['draw', 'default', 'assemble', 'reveal'],
  'arrow-up-down': ['draw', 'default', 'nudge', 'flip', 'reveal'],
  'arrow-up-from-dot': ['draw', 'default', 'reveal'],
  'arrow-up-from-line': ['draw', 'default', 'reveal'],
  'arrow-up-left': ['draw', 'default', 'active', 'nudge', 'reveal'],
  'arrow-up-narrow-wide': ['draw', 'default', 'flip', 'reveal'],
  'arrow-up-right': ['draw', 'default', 'active', 'nudge', 'reveal'],
  'arrow-up-to-line': ['draw', 'default', 'reveal'],
  'arrow-up-wide-narrow': ['draw', 'default', 'flip', 'reveal'],
  'arrow-up-z-a': ['draw', 'default', 'assemble', 'reveal'],
  'arrows-up-from-line': ['draw', 'default', 'reveal'],
  asterisk: ['draw', 'default', 'reveal'],
  astroid: ['draw', 'default', 'hold', 'reveal'],
  'at-sign': ['draw', 'default', 'reveal'],
  atom: ['draw', 'default', 'hold', 'idle', 'reveal'],
  'audio-lines': ['draw', 'default', 'pulse', 'reveal'],
  'audio-lines-x': ['draw', 'default', 'reveal'],
  'audio-waveform': ['draw', 'default', 'reveal'],
  award: ['draw', 'default', 'reveal'],
  axe: ['draw', 'default', 'reveal'],
  'axis-3d': ['draw', 'default', 'reveal'],
  baby: ['draw', 'default', 'hold', 'reveal'],
  backpack: ['draw', 'default', 'hold', 'reveal'],
  badge: ['draw', 'default', 'drop', 'reveal'],
  'badge-alert': ['draw', 'default', 'drop', 'alert', 'reveal'],
  'badge-cent': ['draw', 'default', 'drop', 'reveal'],
  'badge-check': ['draw', 'default', 'drop', 'reveal'],
  'badge-dollar-sign': ['draw', 'default', 'drop', 'reveal'],
  'badge-euro': ['draw', 'default', 'drop', 'reveal'],
  'badge-indian-rupee': ['draw', 'default', 'drop', 'reveal'],
  'badge-info': ['draw', 'default', 'drop', 'reveal'],
  'badge-japanese-yen': ['draw', 'default', 'drop', 'reveal'],
  'badge-minus': ['draw', 'default', 'drop', 'reveal'],
  'badge-percent': ['draw', 'default', 'drop', 'reveal'],
  'badge-plus': ['draw', 'default', 'drop', 'reveal'],
  'badge-pound-sterling': ['draw', 'default', 'drop', 'reveal'],
  'badge-question-mark': ['draw', 'default', 'drop', 'alert', 'reveal'],
  'badge-russian-ruble': ['draw', 'default', 'drop', 'reveal'],
  'badge-swiss-franc': ['draw', 'default', 'drop', 'reveal'],
  'badge-turkish-lira': ['draw', 'default', 'drop', 'reveal'],
  'badge-x': ['draw', 'default', 'drop', 'reveal'],
  'baggage-claim': ['draw', 'default', 'hold', 'bounce', 'reveal'],
  balloon: ['draw', 'default', 'hold', 'reveal'],
  ban: ['draw', 'default', 'reveal'],
  banana: ['draw', 'default', 'hold', 'reveal'],
  bandage: ['draw', 'default', 'hold', 'reveal'],
  banknote: ['draw', 'default', 'reveal'],
  'banknote-arrow-down': ['draw', 'default', 'reveal'],
  'banknote-arrow-up': ['draw', 'default', 'reveal'],
  'banknote-check': ['draw', 'default', 'reveal'],
  'banknote-x': ['draw', 'default', 'reveal'],
  barcode: ['draw', 'default', 'hold', 'reveal'],
  barrel: ['draw', 'default', 'hold', 'reveal'],
  baseline: ['draw', 'default', 'reveal'],
  bath: ['draw', 'default', 'hold', 'reveal'],
  battery: ['draw', 'default', 'pulse', 'reveal'],
  'battery-charging': ['draw', 'default', 'pulse', 'reveal'],
  'battery-full': ['draw', 'default', 'pulse', 'reveal'],
  'battery-low': ['draw', 'default', 'pulse', 'reveal'],
  'battery-medium': ['draw', 'default', 'pulse', 'reveal'],
  'battery-plus': ['draw', 'default', 'pulse', 'reveal'],
  'battery-warning': ['draw', 'default', 'pulse', 'reveal'],
  beaker: ['draw', 'default', 'hold', 'reveal'],
  bean: ['draw', 'default', 'reveal'],
  'bean-off': ['draw', 'default', 'strike', 'reveal'],
  bed: ['draw', 'default', 'hold', 'reveal'],
  'bed-double': ['draw', 'default', 'hold', 'reveal'],
  'bed-single': ['draw', 'default', 'hold', 'reveal'],
  beef: ['draw', 'default', 'reveal'],
  'beef-off': ['draw', 'default', 'alert', 'strike', 'reveal'],
  beer: ['draw', 'default', 'reveal'],
  'beer-off': ['draw', 'default', 'strike', 'reveal'],
  bell: ['draw', 'default', 'alert', 'spark', 'reveal'],
  'bell-check': ['draw', 'default', 'ring', 'reveal'],
  'bell-dot': ['draw', 'default', 'ring', 'reveal'],
  'bell-electric': ['draw', 'default', 'reveal'],
  'bell-minus': ['draw', 'default', 'ring', 'reveal'],
  'bell-off': ['draw', 'default', 'alert', 'strike', 'reveal'],
  'bell-plus': ['draw', 'default', 'ring', 'reveal'],
  'bell-ring': ['draw', 'default', 'alert', 'reveal'],
  'between-horizontal-end': ['draw', 'default', 'reveal'],
  'between-horizontal-start': ['draw', 'default', 'reveal'],
  'between-vertical-end': ['draw', 'default', 'reveal'],
  'between-vertical-start': ['draw', 'default', 'reveal'],
  'biceps-flexed': ['draw', 'default', 'hold', 'reveal'],
  bike: ['draw', 'default', 'hold', 'reveal'],
  binary: ['draw', 'default', 'reveal'],
  binoculars: ['draw', 'default', 'hold', 'reveal'],
  biohazard: ['draw', 'default', 'hold', 'reveal'],
  bird: ['draw', 'default', 'hold', 'reveal'],
  birdhouse: ['draw', 'default', 'hold', 'reveal'],
  bitcoin: ['draw', 'default', 'reveal'],
  blend: ['draw', 'default', 'reveal'],
  blender: ['draw', 'default', 'hold', 'reveal'],
  blinds: ['draw', 'default', 'hold', 'reveal'],
  blocks: ['draw', 'default', 'reveal'],
  bluetooth: ['draw', 'default', 'reveal'],
  'bluetooth-connected': ['draw', 'default', 'reveal'],
  'bluetooth-off': ['draw', 'default', 'strike', 'reveal'],
  'bluetooth-searching': ['draw', 'default', 'reveal'],
  bold: ['draw', 'default', 'reveal'],
  bolt: ['draw', 'default', 'reveal'],
  bomb: ['draw', 'default', 'hold', 'reveal'],
  bone: ['draw', 'default', 'reveal'],
  'bone-fracture': ['draw', 'default', 'reveal'],
  book: ['draw', 'default', 'reveal'],
  'book-a': ['draw', 'default', 'mark', 'reveal'],
  'book-alert': ['draw', 'default', 'reveal'],
  'book-audio': ['draw', 'default', 'mark', 'reveal'],
  'book-check': ['draw', 'default', 'reveal'],
  'book-copy': ['draw', 'default', 'reveal'],
  'book-dashed': ['draw', 'default', 'reveal'],
  'book-down': ['draw', 'default', 'mark', 'reveal'],
  'book-headphones': ['draw', 'default', 'mark', 'reveal'],
  'book-heart': ['draw', 'default', 'mark', 'reveal'],
  'book-image': ['draw', 'default', 'mark', 'reveal'],
  'book-key': ['draw', 'default', 'mark', 'reveal'],
  'book-lock': ['draw', 'default', 'mark', 'reveal'],
  'book-marked': ['draw', 'default', 'mark', 'reveal'],
  'book-minus': ['draw', 'default', 'mark', 'reveal'],
  'book-open': ['draw', 'default', 'reveal'],
  'book-open-check': ['draw', 'default', 'reveal'],
  'book-open-text': ['draw', 'default', 'reveal'],
  'book-plus': ['draw', 'default', 'mark', 'reveal'],
  'book-search': ['draw', 'default', 'reveal'],
  'book-text': ['draw', 'default', 'mark', 'reveal'],
  'book-type': ['draw', 'default', 'mark', 'reveal'],
  'book-up': ['draw', 'default', 'mark', 'reveal'],
  'book-up-2': ['draw', 'default', 'mark', 'reveal'],
  'book-user': ['draw', 'default', 'mark', 'reveal'],
  'book-x': ['draw', 'default', 'mark', 'reveal'],
  bookmark: ['draw', 'default', 'wave', 'pulse', 'reveal'],
  'bookmark-check': ['draw', 'default', 'wave', 'reveal'],
  'bookmark-minus': ['draw', 'default', 'wave', 'reveal'],
  'bookmark-off': ['draw', 'default', 'wave', 'strike', 'reveal'],
  'bookmark-plus': ['draw', 'default', 'wave', 'reveal'],
  'bookmark-x': ['draw', 'default', 'wave', 'reveal'],
  'boom-box': ['draw', 'default', 'hold', 'reveal'],
  bot: ['draw', 'default', 'reveal'],
  'bot-message-square': ['draw', 'default', 'reveal'],
  'bot-off': ['draw', 'default', 'strike', 'reveal'],
  'bottle-wine': ['draw', 'default', 'hold', 'reveal'],
  'bow-arrow': ['draw', 'default', 'hold', 'reveal'],
  box: ['draw', 'default', 'hold', 'reveal'],
  boxes: ['draw', 'default', 'hold', 'reveal'],
  braces: ['draw', 'default', 'reveal'],
  brackets: ['draw', 'default', 'hold', 'reveal'],
  brain: ['draw', 'default', 'reveal'],
  'brain-circuit': ['draw', 'default', 'reveal'],
  'brain-cog': ['draw', 'default', 'reveal'],
  'brick-wall': ['draw', 'default', 'hold', 'reveal'],
  'brick-wall-fire': ['draw', 'default', 'hold', 'reveal'],
  'brick-wall-shield': ['draw', 'default', 'hold', 'reveal'],
  briefcase: ['draw', 'default', 'alert', 'reveal'],
  'briefcase-business': ['draw', 'default', 'reveal'],
  'briefcase-conveyor-belt': ['draw', 'default', 'reveal'],
  'briefcase-medical': ['draw', 'default', 'reveal'],
  'bring-to-front': ['draw', 'default', 'hold', 'reveal'],
  broccoli: ['draw', 'default', 'hold', 'reveal'],
  broom: ['draw', 'default', 'hold', 'reveal'],
  'broom-sparkles': ['draw', 'default', 'hold', 'reveal'],
  brush: ['draw', 'default', 'reveal'],
  'brush-cleaning': ['draw', 'default', 'reveal'],
  bubbles: ['draw', 'default', 'hold', 'reveal'],
  bug: ['draw', 'default', 'reveal'],
  'bug-off': ['draw', 'default', 'strike', 'reveal'],
  'bug-play': ['draw', 'default', 'reveal'],
  building: ['draw', 'default', 'pulse', 'reveal'],
  'building-2': ['draw', 'default', 'pulse', 'reveal'],
  bus: ['draw', 'default', 'hold', 'reveal'],
  'bus-front': ['draw', 'default', 'hold', 'reveal'],
  cable: ['draw', 'default', 'reveal'],
  'cable-car': ['draw', 'default', 'reveal'],
  cake: ['draw', 'default', 'pulse', 'reveal'],
  'cake-slice': ['draw', 'default', 'reveal'],
  calculator: ['draw', 'default', 'hold', 'reveal'],
  calendar: ['draw', 'default', 'pulse', 'reveal'],
  'calendar-1': ['draw', 'default', 'quick', 'reveal'],
  'calendar-arrow-down': ['draw', 'default', 'nudge', 'reveal'],
  'calendar-arrow-up': ['draw', 'default', 'nudge', 'reveal'],
  'calendar-check': ['draw', 'default', 'mark', 'reveal'],
  'calendar-check-2': ['draw', 'default', 'pop', 'reveal'],
  'calendar-clock': ['draw', 'default', 'reveal'],
  'calendar-cog': ['draw', 'default', 'spin', 'reveal'],
  'calendar-days': ['draw', 'default', 'reveal'],
  'calendar-fold': ['draw', 'default', 'flip', 'reveal'],
  'calendar-heart': ['draw', 'default', 'pulse', 'beat', 'reveal'],
  'calendar-minus': ['draw', 'default', 'bounce', 'reveal'],
  'calendar-minus-2': ['draw', 'default', 'bounce', 'reveal'],
  'calendar-off': ['draw', 'default', 'alert', 'strike', 'reveal'],
  'calendar-plus': ['draw', 'default', 'bounce', 'reveal'],
  'calendar-plus-2': ['draw', 'default', 'bounce', 'reveal'],
  'calendar-range': ['draw', 'default', 'quick', 'reveal'],
  'calendar-search': ['draw', 'default', 'shake', 'reveal'],
  'calendar-sync': ['draw', 'default', 'spin', 'reveal'],
  'calendar-x': ['draw', 'default', 'snap', 'reveal'],
  'calendar-x-2': ['draw', 'default', 'snap', 'reveal'],
  calendars: ['draw', 'default', 'hold', 'reveal'],
  camera: ['draw', 'default', 'reveal'],
  'camera-off': ['draw', 'default', 'strike', 'reveal'],
  candy: ['draw', 'default', 'reveal'],
  'candy-cane': ['draw', 'default', 'reveal'],
  'candy-off': ['draw', 'default', 'strike', 'reveal'],
  cannabis: ['draw', 'default', 'reveal'],
  'cannabis-off': ['draw', 'default', 'alert', 'strike', 'reveal'],
  captions: ['draw', 'default', 'reveal'],
  'captions-off': ['draw', 'default', 'strike', 'reveal'],
  car: ['draw', 'default', 'hold', 'idle', 'reveal'],
  'car-front': ['draw', 'default', 'hold', 'reveal'],
  'car-taxi-front': ['draw', 'default', 'hold', 'reveal'],
  caravan: ['draw', 'default', 'hold', 'reveal'],
  'card-sim': ['draw', 'default', 'hold', 'reveal'],
  carrot: ['draw', 'default', 'hold', 'reveal'],
  'case-lower': ['draw', 'default', 'reveal'],
  'case-sensitive': ['draw', 'default', 'reveal'],
  'case-upper': ['draw', 'default', 'reveal'],
  'cassette-tape': ['draw', 'default', 'hold', 'reveal'],
  cast: ['draw', 'default', 'reveal'],
  castle: ['draw', 'default', 'hold', 'reveal'],
  cat: ['draw', 'default', 'hold', 'idle', 'reveal'],
  cctv: ['draw', 'default', 'alert', 'reveal'],
  'cctv-off': ['draw', 'default', 'alert', 'strike', 'reveal'],
  'chart-area': ['draw', 'default', 'reveal'],
  'chart-bar': ['draw', 'default', 'reveal'],
  'chart-bar-big': ['draw', 'default', 'reveal'],
  'chart-bar-decreasing': ['draw', 'default', 'reveal'],
  'chart-bar-increasing': ['draw', 'default', 'reveal'],
  'chart-bar-stacked': ['draw', 'default', 'reveal'],
  'chart-candlestick': ['draw', 'default', 'reveal'],
  'chart-column': ['draw', 'default', 'cascade', 'reveal'],
  'chart-column-big': ['draw', 'default', 'reveal'],
  'chart-column-decreasing': ['draw', 'default', 'reveal'],
  'chart-column-increasing': ['draw', 'default', 'reveal'],
  'chart-column-stacked': ['draw', 'default', 'reveal'],
  'chart-gantt': ['draw', 'default', 'reveal'],
  'chart-line': ['draw', 'default', 'reveal'],
  'chart-network': ['draw', 'default', 'reveal'],
  'chart-no-axes-column': ['draw', 'default', 'reveal'],
  'chart-no-axes-column-decreasing': ['draw', 'default', 'flip', 'reveal'],
  'chart-no-axes-column-increasing': ['draw', 'default', 'flip', 'reveal'],
  'chart-no-axes-combined': ['draw', 'default', 'mark', 'reveal'],
  'chart-no-axes-gantt': ['draw', 'default', 'reveal'],
  'chart-pie': ['draw', 'default', 'reveal'],
  'chart-scatter': ['draw', 'default', 'reveal'],
  'chart-spline': ['draw', 'default', 'reveal'],
  check: ['draw', 'default', 'reveal'],
  'check-check': ['draw', 'default', 'assemble', 'reveal'],
  'check-line': ['draw', 'default', 'reveal'],
  'chef-hat': ['draw', 'default', 'hold', 'reveal'],
  cherry: ['draw', 'default', 'reveal'],
  'chess-bishop': ['draw', 'default', 'hold', 'reveal'],
  'chess-king': ['draw', 'default', 'hold', 'reveal'],
  'chess-knight': ['draw', 'default', 'hold', 'reveal'],
  'chess-pawn': ['draw', 'default', 'hold', 'reveal'],
  'chess-queen': ['draw', 'default', 'hold', 'reveal'],
  'chess-rook': ['draw', 'default', 'hold', 'reveal'],
  'chevron-down': ['draw', 'default', 'active', 'nudge', 'flip', 'reveal'],
  'chevron-first': ['draw', 'default', 'flip', 'reveal'],
  'chevron-last': ['draw', 'default', 'flip', 'reveal'],
  'chevron-left': ['draw', 'default', 'active', 'nudge', 'flip', 'reveal'],
  'chevron-right': ['draw', 'default', 'active', 'nudge', 'flip', 'reveal'],
  'chevron-up': ['draw', 'default', 'active', 'nudge', 'flip', 'reveal'],
  'chevrons-down': ['draw', 'default', 'nudge', 'flip', 'reveal'],
  'chevrons-down-up': ['draw', 'default', 'reveal'],
  'chevrons-left': ['draw', 'default', 'nudge', 'flip', 'reveal'],
  'chevrons-left-right': ['draw', 'default', 'nudge', 'reveal'],
  'chevrons-left-right-ellipsis': ['draw', 'default', 'nudge', 'reveal'],
  'chevrons-right': ['draw', 'default', 'nudge', 'flip', 'reveal'],
  'chevrons-right-left': ['draw', 'default', 'nudge', 'reveal'],
  'chevrons-up': ['draw', 'default', 'nudge', 'flip', 'reveal'],
  'chevrons-up-down': ['draw', 'default', 'active', 'reveal'],
  church: ['draw', 'default', 'hold', 'reveal'],
  cigarette: ['draw', 'default', 'reveal'],
  'cigarette-off': ['draw', 'default', 'strike', 'reveal'],
  circle: ['draw', 'default', 'reveal'],
  'circle-alert': ['draw', 'default', 'alert', 'reveal'],
  'circle-arrow-down': ['draw', 'default', 'hold', 'reveal'],
  'circle-arrow-left': ['draw', 'default', 'hold', 'reveal'],
  'circle-arrow-out-down-left': ['draw', 'default', 'hold', 'reveal'],
  'circle-arrow-out-down-right': ['draw', 'default', 'hold', 'reveal'],
  'circle-arrow-out-up-left': ['draw', 'default', 'hold', 'reveal'],
  'circle-arrow-out-up-right': ['draw', 'default', 'hold', 'reveal'],
  'circle-arrow-right': ['draw', 'default', 'hold', 'reveal'],
  'circle-arrow-up': ['draw', 'default', 'hold', 'reveal'],
  'circle-check': ['draw', 'default', 'mark', 'reveal'],
  'circle-check-big': ['draw', 'default', 'reveal'],
  'circle-chevron-down': ['draw', 'default', 'hold', 'reveal'],
  'circle-chevron-left': ['draw', 'default', 'hold', 'reveal'],
  'circle-chevron-right': ['draw', 'default', 'hold', 'reveal'],
  'circle-chevron-up': ['draw', 'default', 'hold', 'reveal'],
  'circle-dashed': ['draw', 'default', 'reveal'],
  'circle-divide': ['draw', 'default', 'reveal'],
  'circle-dollar-sign': ['draw', 'default', 'reveal'],
  'circle-dot': ['draw', 'default', 'reveal'],
  'circle-dot-dashed': ['draw', 'default', 'reveal'],
  'circle-ellipsis': ['draw', 'default', 'reveal'],
  'circle-equal': ['draw', 'default', 'reveal'],
  'circle-euro': ['draw', 'default', 'reveal'],
  'circle-fading-arrow-up': ['draw', 'default', 'reveal'],
  'circle-fading-plus': ['draw', 'default', 'reveal'],
  'circle-gauge': ['draw', 'default', 'reveal'],
  'circle-minus': ['draw', 'default', 'reveal'],
  'circle-off': ['draw', 'default', 'strike', 'reveal'],
  'circle-parking': ['draw', 'default', 'reveal'],
  'circle-parking-off': ['draw', 'default', 'strike', 'reveal'],
  'circle-pause': ['draw', 'default', 'reveal'],
  'circle-percent': ['draw', 'default', 'reveal'],
  'circle-pile': ['draw', 'default', 'reveal'],
  'circle-play': ['draw', 'default', 'reveal'],
  'circle-plus': ['draw', 'default', 'mark', 'reveal'],
  'circle-pound-sterling': ['draw', 'default', 'reveal'],
  'circle-power': ['draw', 'default', 'reveal'],
  'circle-question-mark': ['draw', 'default', 'alert', 'reveal'],
  'circle-slash': ['draw', 'default', 'reveal'],
  'circle-slash-2': ['draw', 'default', 'alert', 'reveal'],
  'circle-small': ['draw', 'default', 'reveal'],
  'circle-star': ['draw', 'default', 'reveal'],
  'circle-stop': ['draw', 'default', 'reveal'],
  'circle-user': ['draw', 'default', 'reveal'],
  'circle-user-round': ['draw', 'default', 'reveal'],
  'circle-x': ['draw', 'default', 'reveal'],
  'circuit-board': ['draw', 'default', 'hold', 'reveal'],
  citrus: ['draw', 'default', 'hold', 'reveal'],
  clapperboard: ['draw', 'default', 'reveal'],
  clipboard: ['draw', 'default', 'bounce', 'reveal'],
  'clipboard-check': ['draw', 'default', 'mark', 'reveal'],
  'clipboard-clock': ['draw', 'default', 'spin', 'reveal'],
  'clipboard-copy': ['draw', 'default', 'peel', 'hold', 'reveal'],
  'clipboard-list': ['draw', 'default', 'quick', 'active', 'reveal'],
  'clipboard-minus': ['draw', 'default', 'bounce', 'reveal'],
  'clipboard-paste': ['draw', 'default', 'nudge', 'reveal'],
  'clipboard-pen': ['draw', 'default', 'write', 'nudge', 'reveal'],
  'clipboard-pen-line': ['draw', 'default', 'write', 'alert', 'reveal'],
  'clipboard-plus': ['draw', 'default', 'bounce', 'reveal'],
  'clipboard-type': ['draw', 'default', 'quick', 'reveal'],
  'clipboard-x': ['draw', 'default', 'mark', 'reveal'],
  clock: ['draw', 'default', 'spin', 'reveal'],
  'clock-1': ['draw', 'default', 'spin', 'reveal'],
  'clock-10': ['draw', 'default', 'spin', 'reveal'],
  'clock-11': ['draw', 'default', 'spin', 'reveal'],
  'clock-12': ['draw', 'default', 'spin', 'reveal'],
  'clock-2': ['draw', 'default', 'spin', 'reveal'],
  'clock-3': ['draw', 'default', 'spin', 'reveal'],
  'clock-4': ['draw', 'default', 'spin', 'reveal'],
  'clock-5': ['draw', 'default', 'spin', 'reveal'],
  'clock-6': ['draw', 'default', 'spin', 'reveal'],
  'clock-7': ['draw', 'default', 'spin', 'reveal'],
  'clock-8': ['draw', 'default', 'spin', 'reveal'],
  'clock-9': ['draw', 'default', 'spin', 'reveal'],
  'clock-alert': ['draw', 'default', 'spin', 'reveal'],
  'clock-arrow-down': ['draw', 'default', 'hold', 'spin', 'reveal'],
  'clock-arrow-left': ['draw', 'default', 'hold', 'spin', 'reveal'],
  'clock-arrow-right': ['draw', 'default', 'hold', 'spin', 'reveal'],
  'clock-arrow-up': ['draw', 'default', 'hold', 'spin', 'reveal'],
  'clock-check': ['draw', 'default', 'spin', 'reveal'],
  'clock-fading': ['draw', 'default', 'spin', 'reveal'],
  'clock-plus': ['draw', 'default', 'spin', 'reveal'],
  'closed-caption': ['draw', 'default', 'hold', 'reveal'],
  cloud: ['draw', 'default', 'reveal'],
  'cloud-alert': ['draw', 'default', 'reveal'],
  'cloud-backup': ['draw', 'default', 'hold', 'reveal'],
  'cloud-check': ['draw', 'default', 'reveal'],
  'cloud-cog': ['draw', 'default', 'reveal'],
  'cloud-download': ['draw', 'default', 'reveal'],
  'cloud-drizzle': ['draw', 'default', 'reveal'],
  'cloud-fog': ['draw', 'default', 'reveal'],
  'cloud-hail': ['draw', 'default', 'reveal'],
  'cloud-lightning': ['draw', 'default', 'reveal'],
  'cloud-moon': ['draw', 'default', 'reveal'],
  'cloud-moon-rain': ['draw', 'default', 'reveal'],
  'cloud-off': ['draw', 'default', 'strike', 'reveal'],
  'cloud-rain': ['draw', 'default', 'reveal'],
  'cloud-rain-wind': ['draw', 'default', 'reveal'],
  'cloud-snow': ['draw', 'default', 'reveal'],
  'cloud-sun': ['draw', 'default', 'reveal'],
  'cloud-sun-rain': ['draw', 'default', 'reveal'],
  'cloud-sync': ['draw', 'default', 'hold', 'reveal'],
  'cloud-upload': ['draw', 'default', 'active', 'reveal'],
  cloudy: ['draw', 'default', 'hold', 'reveal'],
  clover: ['draw', 'default', 'hold', 'reveal'],
  club: ['draw', 'default', 'hold', 'reveal'],
  code: ['draw', 'default', 'hold', 'nudge', 'reveal'],
  'code-xml': ['draw', 'default', 'hold', 'reveal'],
  coffee: ['draw', 'default', 'hold', 'reveal'],
  cog: ['draw', 'default', 'reveal'],
  coins: ['draw', 'default', 'hold', 'reveal'],
  'columns-2': ['draw', 'default', 'reveal'],
  'columns-3': ['draw', 'default', 'reveal'],
  'columns-3-cog': ['draw', 'default', 'reveal'],
  'columns-4': ['draw', 'default', 'reveal'],
  combine: ['draw', 'default', 'hold', 'reveal'],
  command: ['draw', 'default', 'reveal'],
  compass: ['draw', 'default', 'reveal'],
  component: ['draw', 'default', 'hold', 'reveal'],
  computer: ['draw', 'default', 'hold', 'reveal'],
  'concierge-bell': ['draw', 'default', 'hold', 'reveal'],
  cone: ['draw', 'default', 'hold', 'reveal'],
  construction: ['draw', 'default', 'hold', 'reveal'],
  contact: ['draw', 'default', 'reveal'],
  'contact-round': ['draw', 'default', 'reveal'],
  container: ['draw', 'default', 'hold', 'reveal'],
  contrast: ['draw', 'default', 'reveal'],
  cookie: ['draw', 'default', 'hold', 'reveal'],
  'cooking-pot': ['draw', 'default', 'hold', 'reveal'],
  copy: ['draw', 'default', 'active', 'reveal'],
  'copy-check': ['draw', 'default', 'peel', 'mark', 'reveal'],
  'copy-minus': ['draw', 'default', 'peel', 'reveal'],
  'copy-plus': ['draw', 'default', 'peel', 'reveal'],
  'copy-slash': ['draw', 'default', 'peel', 'reveal'],
  'copy-x': ['draw', 'default', 'peel', 'reveal'],
  copyleft: ['draw', 'default', 'hold', 'reveal'],
  copyright: ['draw', 'default', 'hold', 'reveal'],
  'corner-down-left': ['draw', 'default', 'assemble', 'nudge', 'reveal'],
  'corner-down-right': ['draw', 'default', 'assemble', 'nudge', 'reveal'],
  'corner-left-down': ['draw', 'default', 'assemble', 'nudge', 'reveal'],
  'corner-left-up': ['draw', 'default', 'assemble', 'nudge', 'reveal'],
  'corner-right-down': ['draw', 'default', 'assemble', 'nudge', 'reveal'],
  'corner-right-up': ['draw', 'default', 'assemble', 'nudge', 'reveal'],
  'corner-up-left': ['draw', 'default', 'assemble', 'nudge', 'reveal'],
  'corner-up-right': ['draw', 'default', 'assemble', 'nudge', 'reveal'],
  cpu: ['draw', 'default', 'cascade', 'reveal'],
  'creative-commons': ['draw', 'default', 'hold', 'reveal'],
  'credit-card': ['draw', 'default', 'pulse', 'reveal'],
  croissant: ['draw', 'default', 'hold', 'reveal'],
  crop: ['draw', 'default', 'reveal'],
  cross: ['draw', 'default', 'hold', 'reveal'],
  crosshair: ['draw', 'default', 'hold', 'reveal'],
  crown: ['draw', 'default', 'reveal'],
  cuboid: ['draw', 'default', 'hold', 'reveal'],
  'cup-soda': ['draw', 'default', 'hold', 'reveal'],
  currency: ['draw', 'default', 'reveal'],
  cylinder: ['draw', 'default', 'hold', 'reveal'],
  dam: ['draw', 'default', 'hold', 'reveal'],
  database: ['draw', 'default', 'reveal'],
  'database-arrow-down': ['draw', 'default', 'hold', 'reveal'],
  'database-arrow-up': ['draw', 'default', 'hold', 'reveal'],
  'database-backup': ['draw', 'default', 'hold', 'reveal'],
  'database-check': ['draw', 'default', 'hold', 'pulse', 'reveal'],
  'database-minus': ['draw', 'default', 'hold', 'pulse', 'reveal'],
  'database-plus': ['draw', 'default', 'hold', 'reveal'],
  'database-search': ['draw', 'default', 'hold', 'reveal'],
  'database-x': ['draw', 'default', 'hold', 'reveal'],
  'database-zap': ['draw', 'default', 'hold', 'reveal'],
  'decimals-arrow-left': ['draw', 'default', 'reveal'],
  'decimals-arrow-right': ['draw', 'default', 'reveal'],
  delete: ['draw', 'default', 'hold', 'reveal'],
  dessert: ['draw', 'default', 'hold', 'reveal'],
  diameter: ['draw', 'default', 'hold', 'reveal'],
  diamond: ['draw', 'default', 'reveal'],
  'diamond-minus': ['draw', 'default', 'reveal'],
  'diamond-percent': ['draw', 'default', 'reveal'],
  'diamond-plus': ['draw', 'default', 'reveal'],
  'dice-1': ['draw', 'default', 'reveal'],
  'dice-2': ['draw', 'default', 'reveal'],
  'dice-3': ['draw', 'default', 'reveal'],
  'dice-4': ['draw', 'default', 'reveal'],
  'dice-5': ['draw', 'default', 'reveal'],
  'dice-6': ['draw', 'default', 'reveal'],
  dices: ['draw', 'default', 'hold', 'reveal'],
  diff: ['draw', 'default', 'reveal'],
  disc: ['draw', 'default', 'reveal'],
  'disc-2': ['draw', 'default', 'reveal'],
  'disc-3': ['draw', 'default', 'active', 'reveal'],
  'disc-album': ['draw', 'default', 'reveal'],
  divide: ['draw', 'default', 'reveal'],
  dna: ['draw', 'default', 'reveal'],
  'dna-off': ['draw', 'default', 'strike', 'reveal'],
  dock: ['draw', 'default', 'hold', 'reveal'],
  dog: ['draw', 'default', 'hold', 'idle', 'reveal'],
  'dollar-sign': ['draw', 'default', 'reveal'],
  donut: ['draw', 'default', 'hold', 'reveal'],
  'door-closed': ['draw', 'default', 'hold', 'reveal'],
  'door-closed-locked': ['draw', 'default', 'hold', 'reveal'],
  'door-open': ['draw', 'default', 'hold', 'reveal'],
  dot: ['draw', 'default', 'hold', 'reveal'],
  download: ['draw', 'default', 'hold', 'nudge', 'assemble', 'reveal'],
  'drafting-compass': ['draw', 'default', 'hold', 'reveal'],
  drama: ['draw', 'default', 'hold', 'reveal'],
  drill: ['draw', 'default', 'hold', 'reveal'],
  drone: ['draw', 'default', 'hold', 'reveal'],
  droplet: ['draw', 'default', 'reveal'],
  'droplet-off': ['draw', 'default', 'strike', 'reveal'],
  droplets: ['draw', 'default', 'hold', 'reveal'],
  drum: ['draw', 'default', 'pulse', 'reveal'],
  drumstick: ['draw', 'default', 'hold', 'reveal'],
  dumbbell: ['draw', 'default', 'hold', 'reveal'],
  ear: ['draw', 'default', 'reveal'],
  'ear-off': ['draw', 'default', 'strike', 'reveal'],
  earth: ['draw', 'default', 'hold', 'reveal'],
  'earth-lock': ['draw', 'default', 'hold', 'reveal'],
  eclipse: ['draw', 'default', 'reveal'],
  egg: ['draw', 'default', 'reveal'],
  'egg-fried': ['draw', 'default', 'reveal'],
  'egg-off': ['draw', 'default', 'strike', 'reveal'],
  eject: ['draw', 'default', 'reveal'],
  ellipse: ['draw', 'default', 'hold', 'reveal'],
  ellipsis: ['draw', 'default', 'reveal'],
  'ellipsis-vertical': ['draw', 'default', 'reveal'],
  equal: ['draw', 'default', 'reveal'],
  'equal-approximately': ['draw', 'default', 'reveal'],
  'equal-not': ['draw', 'default', 'reveal'],
  eraser: ['draw', 'default', 'hold', 'reveal'],
  'ethernet-port': ['draw', 'default', 'hold', 'reveal'],
  euro: ['draw', 'default', 'reveal'],
  'ev-charger': ['draw', 'default', 'hold', 'reveal'],
  expand: ['draw', 'default', 'hold', 'reveal'],
  'external-link': ['draw', 'default', 'hold', 'assemble', 'nudge', 'reveal'],
  eye: ['draw', 'default', 'idle', 'reveal'],
  'eye-closed': ['draw', 'default', 'reveal'],
  'eye-dashed': ['draw', 'default', 'reveal'],
  'eye-off': ['draw', 'default', 'alert', 'reveal', 'strike'],
  'face-angry': ['draw', 'default', 'idle', 'reveal'],
  'face-expressionless': ['draw', 'default', 'idle', 'reveal'],
  'face-grinning': ['draw', 'default', 'idle', 'reveal'],
  'face-neutral': ['draw', 'default', 'idle', 'reveal'],
  'face-slightly-frowning': ['draw', 'default', 'idle', 'reveal'],
  'face-slightly-smiling': ['draw', 'default', 'idle', 'reveal'],
  'face-slightly-smiling-plus': ['draw', 'default', 'idle', 'reveal'],
  factory: ['draw', 'default', 'hold', 'reveal'],
  fan: ['draw', 'default', 'hold', 'reveal'],
  'fast-forward': ['draw', 'default', 'hold', 'flip', 'reveal'],
  feather: ['draw', 'default', 'hold', 'reveal'],
  fence: ['draw', 'default', 'hold', 'reveal'],
  'ferris-wheel': ['draw', 'default', 'hold', 'reveal'],
  file: ['draw', 'default', 'pulse', 'reveal'],
  'file-archive': ['draw', 'default', 'pulse', 'reveal'],
  'file-axis-3d': ['draw', 'default', 'pulse', 'reveal'],
  'file-badge': ['draw', 'default', 'chida', 'pulse', 'reveal'],
  'file-box': ['draw', 'default', 'pulse', 'reveal'],
  'file-braces': ['draw', 'default', 'pulse', 'reveal'],
  'file-braces-corner': ['draw', 'default', 'pulse', 'reveal'],
  'file-chart-column': ['draw', 'default', 'pulse', 'reveal'],
  'file-chart-column-increasing': ['draw', 'default', 'pulse', 'reveal'],
  'file-chart-line': ['draw', 'default', 'pulse', 'reveal'],
  'file-chart-pie': ['draw', 'default', 'pulse', 'reveal'],
  'file-check': ['draw', 'default', 'mark', 'pulse', 'reveal'],
  'file-check-corner': ['draw', 'default', 'mark', 'pulse', 'reveal'],
  'file-clock': ['draw', 'default', 'pulse', 'reveal'],
  'file-code': ['draw', 'default', 'pulse', 'reveal'],
  'file-code-corner': ['draw', 'default', 'pulse', 'reveal'],
  'file-cog': ['draw', 'default', 'pulse', 'reveal'],
  'file-diff': ['draw', 'default', 'pulse', 'reveal'],
  'file-digit': ['draw', 'default', 'pulse', 'reveal'],
  'file-down': ['draw', 'default', 'pulse', 'reveal'],
  'file-exclamation-point': ['draw', 'default', 'alert', 'pulse', 'reveal'],
  'file-headphone': ['draw', 'default', 'pulse', 'reveal'],
  'file-heart': ['draw', 'default', 'pulse', 'reveal'],
  'file-image': ['draw', 'default', 'pulse', 'reveal'],
  'file-input': ['draw', 'default', 'pulse', 'reveal'],
  'file-key': ['draw', 'default', 'pulse', 'reveal'],
  'file-lock': ['draw', 'default', 'pulse', 'reveal'],
  'file-minus': ['draw', 'default', 'pulse', 'reveal'],
  'file-minus-corner': ['draw', 'default', 'pulse', 'reveal'],
  'file-music': ['draw', 'default', 'pulse', 'reveal'],
  'file-output': ['draw', 'default', 'pulse', 'reveal'],
  'file-pen': ['draw', 'default', 'pulse', 'reveal'],
  'file-pen-line': ['draw', 'default', 'pulse', 'reveal'],
  'file-play': ['draw', 'default', 'pulse', 'reveal'],
  'file-plus': ['draw', 'default', 'pulse', 'reveal'],
  'file-plus-corner': ['draw', 'default', 'pulse', 'reveal'],
  'file-question-mark': ['draw', 'default', 'pulse', 'reveal'],
  'file-scan': ['draw', 'default', 'pulse', 'reveal'],
  'file-search': ['draw', 'default', 'pulse', 'reveal'],
  'file-search-corner': ['draw', 'default', 'pulse', 'reveal'],
  'file-signal': ['draw', 'default', 'pulse', 'reveal'],
  'file-sliders': ['draw', 'default', 'pulse', 'reveal'],
  'file-spreadsheet': ['draw', 'default', 'pulse', 'reveal'],
  'file-stack': ['draw', 'default', 'pulse', 'reveal'],
  'file-symlink': ['draw', 'default', 'pulse', 'reveal'],
  'file-terminal': ['draw', 'default', 'pulse', 'reveal'],
  'file-text': ['draw', 'default', 'pulse', 'reveal'],
  'file-type': ['draw', 'default', 'pulse', 'reveal'],
  'file-type-corner': ['draw', 'default', 'pulse', 'reveal'],
  'file-up': ['draw', 'default', 'pulse', 'reveal'],
  'file-user': ['draw', 'default', 'pulse', 'reveal'],
  'file-video-camera': ['draw', 'default', 'pulse', 'reveal'],
  'file-volume': ['draw', 'default', 'pulse', 'reveal'],
  'file-x': ['draw', 'default', 'pulse', 'reveal'],
  'file-x-corner': ['draw', 'default', 'pulse', 'reveal'],
  files: ['draw', 'default', 'hold', 'reveal'],
  film: ['draw', 'default', 'hold', 'reveal'],
  'fingerprint-pattern': ['draw', 'default', 'hold', 'reveal'],
  'fire-extinguisher': ['draw', 'default', 'hold', 'reveal'],
  fish: ['draw', 'default', 'idle', 'reveal'],
  'fish-off': ['draw', 'default', 'reveal'],
  'fish-symbol': ['draw', 'default', 'reveal'],
  'fishing-hook': ['draw', 'default', 'hold', 'reveal'],
  'fishing-rod': ['draw', 'default', 'hold', 'reveal'],
  flag: ['draw', 'default', 'reveal'],
  'flag-off': ['draw', 'default', 'strike', 'reveal'],
  'flag-triangle-left': ['draw', 'default', 'reveal'],
  'flag-triangle-right': ['draw', 'default', 'reveal'],
  flame: ['draw', 'default', 'hold', 'spark', 'reveal'],
  'flame-kindling': ['draw', 'default', 'hold', 'reveal'],
  flashlight: ['draw', 'default', 'reveal'],
  'flashlight-off': ['draw', 'default', 'strike', 'reveal'],
  'flask-conical': ['draw', 'default', 'reveal'],
  'flask-conical-off': ['draw', 'default', 'strike', 'reveal'],
  'flask-round': ['draw', 'default', 'reveal'],
  'flip-horizontal-2': ['draw', 'default', 'reveal'],
  'flip-vertical-2': ['draw', 'default', 'reveal'],
  flower: ['draw', 'default', 'hold', 'reveal'],
  'flower-2': ['draw', 'default', 'hold', 'reveal'],
  focus: ['draw', 'default', 'hold', 'reveal'],
  'fold-horizontal': ['draw', 'default', 'reveal'],
  'fold-vertical': ['draw', 'default', 'reveal'],
  folder: ['draw', 'default', 'reveal'],
  'folder-archive': ['draw', 'default', 'extra', 'reveal'],
  'folder-bookmark': ['draw', 'default', 'extra', 'reveal'],
  'folder-check': ['draw', 'default', 'extra', 'mark', 'reveal'],
  'folder-clock': ['draw', 'default', 'extra', 'reveal'],
  'folder-closed': ['draw', 'default', 'extra', 'reveal'],
  'folder-code': ['draw', 'default', 'extra', 'reveal'],
  'folder-cog': ['draw', 'default', 'extra', 'active', 'reveal'],
  'folder-dot': ['draw', 'default', 'extra', 'reveal'],
  'folder-down': ['draw', 'default', 'extra', 'active', 'reveal'],
  'folder-git': ['draw', 'default', 'extra', 'reveal'],
  'folder-git-2': ['draw', 'default', 'extra', 'reveal'],
  'folder-heart': ['draw', 'default', 'extra', 'reveal'],
  'folder-input': ['draw', 'default', 'extra', 'reveal'],
  'folder-kanban': ['draw', 'default', 'extra', 'cascade', 'reveal'],
  'folder-key': ['draw', 'default', 'extra', 'reveal'],
  'folder-lock': ['draw', 'default', 'extra', 'reveal'],
  'folder-minus': ['draw', 'default', 'extra', 'reveal'],
  'folder-open': ['draw', 'default', 'reveal'],
  'folder-open-dot': ['draw', 'default', 'extra', 'reveal'],
  'folder-output': ['draw', 'default', 'extra', 'reveal'],
  'folder-pen': ['draw', 'default', 'extra', 'nudge', 'reveal'],
  'folder-plus': ['draw', 'default', 'extra', 'mark', 'reveal'],
  'folder-root': ['draw', 'default', 'extra', 'reveal'],
  'folder-search': ['draw', 'default', 'extra', 'reveal'],
  'folder-search-2': ['draw', 'default', 'extra', 'reveal'],
  'folder-symlink': ['draw', 'default', 'extra', 'reveal'],
  'folder-sync': ['draw', 'default', 'extra', 'active', 'reveal'],
  'folder-tree': ['draw', 'default', 'extra', 'reveal'],
  'folder-up': ['draw', 'default', 'extra', 'active', 'reveal'],
  'folder-x': ['draw', 'default', 'extra', 'mark', 'reveal'],
  folders: ['draw', 'default', 'hold', 'reveal'],
  footprints: ['draw', 'default', 'hold', 'reveal'],
  forklift: ['draw', 'default', 'hold', 'reveal'],
  form: ['draw', 'default', 'hold', 'reveal'],
  forward: ['draw', 'default', 'flip', 'reveal'],
  frame: ['draw', 'default', 'reveal'],
  fuel: ['draw', 'default', 'hold', 'reveal'],
  fullscreen: ['draw', 'default', 'hold', 'reveal'],
  funnel: ['draw', 'default', 'reveal'],
  'funnel-plus': ['draw', 'default', 'reveal'],
  'funnel-x': ['draw', 'default', 'reveal'],
  'gallery-horizontal': ['draw', 'default', 'reveal'],
  'gallery-horizontal-end': ['draw', 'default', 'reveal'],
  'gallery-thumbnails': ['draw', 'default', 'reveal'],
  'gallery-vertical': ['draw', 'default', 'reveal'],
  'gallery-vertical-end': ['draw', 'default', 'reveal'],
  gamepad: ['draw', 'default', 'hold', 'bounce', 'reveal'],
  'gamepad-2': ['draw', 'default', 'hold', 'reveal'],
  'gamepad-directional': ['draw', 'default', 'hold', 'reveal'],
  gauge: ['draw', 'default', 'reveal'],
  gavel: ['draw', 'default', 'reveal'],
  gem: ['draw', 'default', 'hold', 'reveal'],
  'georgian-lari': ['draw', 'default', 'reveal'],
  ghost: ['draw', 'default', 'hold', 'reveal'],
  gift: ['draw', 'default', 'hold', 'reveal'],
  'git-branch': ['draw', 'default', 'flip', 'reveal'],
  'git-branch-minus': ['draw', 'default', 'reveal'],
  'git-branch-plus': ['draw', 'default', 'reveal'],
  'git-commit-horizontal': ['draw', 'default', 'assemble', 'reveal'],
  'git-commit-vertical': ['draw', 'default', 'assemble', 'reveal'],
  'git-compare': ['draw', 'default', 'assemble', 'reveal'],
  'git-compare-arrows': ['draw', 'default', 'assemble', 'reveal'],
  'git-fork': ['draw', 'default', 'assemble', 'reveal'],
  'git-graph': ['draw', 'default', 'reveal'],
  'git-merge': ['draw', 'default', 'flip', 'reveal'],
  'git-merge-conflict': ['draw', 'default', 'assemble', 'reveal'],
  'git-pull-request': ['draw', 'default', 'reveal'],
  'git-pull-request-arrow': ['draw', 'default', 'reveal'],
  'git-pull-request-closed': ['draw', 'default', 'reveal'],
  'git-pull-request-create': ['draw', 'default', 'reveal'],
  'git-pull-request-create-arrow': ['draw', 'default', 'reveal'],
  'git-pull-request-draft': ['draw', 'default', 'reveal'],
  'glass-water': ['draw', 'default', 'hold', 'reveal'],
  glasses: ['draw', 'default', 'hold', 'reveal'],
  globe: ['draw', 'default', 'reveal'],
  'globe-check': ['draw', 'default', 'shake', 'reveal'],
  'globe-lock': ['draw', 'default', 'shake', 'reveal'],
  'globe-off': ['draw', 'default', 'flash', 'flicker', 'strike', 'reveal'],
  'globe-x': ['draw', 'default', 'shake', 'reveal'],
  goal: ['draw', 'default', 'hold', 'reveal'],
  gpu: ['draw', 'default', 'hold', 'reveal'],
  'graduation-cap': ['draw', 'default', 'reveal'],
  grape: ['draw', 'default', 'hold', 'reveal'],
  'grid-2x2': ['draw', 'default', 'flash', 'reveal'],
  'grid-2x2-check': ['draw', 'default', 'flash', 'mark', 'reveal'],
  'grid-2x2-plus': ['draw', 'default', 'flash', 'reveal'],
  'grid-2x2-x': ['draw', 'default', 'flash', 'reveal'],
  'grid-3x2': ['draw', 'default', 'reveal'],
  'grid-3x3': ['draw', 'default', 'reveal'],
  grip: ['draw', 'default', 'reveal'],
  'grip-horizontal': ['draw', 'default', 'reveal'],
  'grip-vertical': ['draw', 'default', 'cascade', 'reveal'],
  group: ['draw', 'default', 'hold', 'reveal'],
  guitar: ['draw', 'default', 'hold', 'reveal'],
  ham: ['draw', 'default', 'hold', 'reveal'],
  hamburger: ['draw', 'default', 'hold', 'reveal'],
  hammer: ['draw', 'default', 'spark', 'reveal'],
  hand: ['draw', 'default', 'reveal'],
  'hand-coins': ['draw', 'default', 'reveal'],
  'hand-fist': ['draw', 'default', 'reveal'],
  'hand-grab': ['draw', 'default', 'reveal'],
  'hand-heart': ['draw', 'default', 'reveal'],
  'hand-helping': ['draw', 'default', 'reveal'],
  'hand-metal': ['draw', 'default', 'reveal'],
  'hand-platter': ['draw', 'default', 'reveal'],
  handbag: ['draw', 'default', 'hold', 'reveal'],
  handshake: ['draw', 'default', 'hold', 'reveal'],
  'hard-drive': ['draw', 'default', 'reveal'],
  'hard-drive-download': ['draw', 'default', 'reveal'],
  'hard-drive-upload': ['draw', 'default', 'reveal'],
  'hard-hat': ['draw', 'default', 'reveal'],
  hash: ['draw', 'default', 'reveal'],
  'hat-glasses': ['draw', 'default', 'reveal'],
  haze: ['draw', 'default', 'hold', 'reveal'],
  hd: ['draw', 'default', 'hold', 'reveal'],
  'hdmi-port': ['draw', 'default', 'hold', 'reveal'],
  heading: ['draw', 'default', 'reveal'],
  'heading-1': ['draw', 'default', 'reveal'],
  'heading-2': ['draw', 'default', 'reveal'],
  'heading-3': ['draw', 'default', 'reveal'],
  'heading-4': ['draw', 'default', 'reveal'],
  'heading-5': ['draw', 'default', 'reveal'],
  'heading-6': ['draw', 'default', 'reveal'],
  'headphone-off': ['draw', 'default', 'strike', 'reveal'],
  headphones: ['draw', 'default', 'hold', 'reveal'],
  headset: ['draw', 'default', 'hold', 'reveal'],
  heart: ['draw', 'default', 'pulse', 'spark', 'reveal'],
  'heart-crack': ['draw', 'default', 'pulse', 'reveal'],
  'heart-handshake': ['draw', 'default', 'pulse', 'reveal'],
  'heart-minus': ['draw', 'default', 'pulse', 'reveal'],
  'heart-off': ['draw', 'default', 'alert', 'strike', 'reveal'],
  'heart-plus': ['draw', 'default', 'pulse', 'reveal'],
  'heart-pulse': ['draw', 'default', 'reveal'],
  'heart-x': ['draw', 'default', 'pulse', 'reveal'],
  heater: ['draw', 'default', 'hold', 'reveal'],
  helicopter: ['draw', 'default', 'hold', 'reveal'],
  hexagon: ['draw', 'default', 'hold', 'reveal'],
  highlighter: ['draw', 'default', 'reveal'],
  hop: ['draw', 'default', 'reveal'],
  'hop-off': ['draw', 'default', 'strike', 'reveal'],
  hospital: ['draw', 'default', 'hold', 'reveal'],
  hotel: ['draw', 'default', 'hold', 'reveal'],
  hourglass: ['draw', 'default', 'hold', 'reveal'],
  house: ['draw', 'default', 'mark', 'reveal'],
  'house-heart': ['draw', 'default', 'reveal'],
  'house-plug': ['draw', 'default', 'reveal'],
  'house-plus': ['draw', 'default', 'reveal'],
  'house-wifi': ['draw', 'default', 'reveal'],
  'ice-cream-bowl': ['draw', 'default', 'hold', 'reveal'],
  'ice-cream-cone': ['draw', 'default', 'hold', 'reveal'],
  'id-card': ['draw', 'default', 'reveal'],
  'id-card-lanyard': ['draw', 'default', 'reveal'],
  image: ['draw', 'default', 'reveal'],
  'image-down': ['draw', 'default', 'active', 'reveal'],
  'image-minus': ['draw', 'default', 'reveal'],
  'image-off': ['draw', 'default', 'alert', 'strike', 'reveal'],
  'image-play': ['draw', 'default', 'reveal'],
  'image-plus': ['draw', 'default', 'reveal'],
  'image-up': ['draw', 'default', 'active', 'reveal'],
  'image-upscale': ['draw', 'default', 'reveal'],
  images: ['draw', 'default', 'active', 'reveal'],
  import: ['draw', 'default', 'hold', 'reveal'],
  inbox: ['draw', 'default', 'reveal'],
  'indian-rupee': ['draw', 'default', 'reveal'],
  infinity: ['draw', 'default', 'reveal'],
  info: ['draw', 'default', 'reveal'],
  'inspection-panel': ['draw', 'default', 'hold', 'reveal'],
  italic: ['draw', 'default', 'reveal'],
  'iteration-ccw': ['draw', 'default', 'flip', 'reveal'],
  'iteration-cw': ['draw', 'default', 'flip', 'reveal'],
  'japanese-yen': ['draw', 'default', 'reveal'],
  joystick: ['draw', 'default', 'hold', 'reveal'],
  kanban: ['draw', 'default', 'reveal'],
  kayak: ['draw', 'default', 'hold', 'reveal'],
  key: ['draw', 'default', 'active', 'reveal'],
  'key-round': ['draw', 'default', 'nudge', 'reveal'],
  'key-square': ['draw', 'default', 'reveal'],
  keyboard: ['draw', 'default', 'reveal'],
  'keyboard-music': ['draw', 'default', 'reveal'],
  'keyboard-off': ['draw', 'default', 'strike', 'reveal'],
  lamp: ['draw', 'default', 'hold', 'reveal'],
  'lamp-ceiling': ['draw', 'default', 'hold', 'reveal'],
  'lamp-desk': ['draw', 'default', 'hold', 'reveal'],
  'lamp-floor': ['draw', 'default', 'hold', 'reveal'],
  'lamp-wall-down': ['draw', 'default', 'hold', 'reveal'],
  'lamp-wall-up': ['draw', 'default', 'hold', 'reveal'],
  'land-plot': ['draw', 'default', 'hold', 'reveal'],
  landmark: ['draw', 'default', 'alert', 'reveal'],
  languages: ['draw', 'default', 'reveal'],
  laptop: ['draw', 'default', 'reveal'],
  'laptop-minimal': ['draw', 'default', 'reveal'],
  'laptop-minimal-check': ['draw', 'default', 'reveal'],
  lasso: ['draw', 'default', 'hold', 'reveal'],
  'lasso-select': ['draw', 'default', 'hold', 'reveal'],
  'layer-arrow-down': ['draw', 'default', 'reveal'],
  'layer-arrow-up': ['draw', 'default', 'reveal'],
  layers: ['draw', 'default', 'nudge', 'merge', 'active', 'reveal'],
  'layers-2': ['draw', 'default', 'hold', 'reveal'],
  'layers-arrow-down': ['draw', 'default', 'hold', 'reveal'],
  'layers-arrow-up': ['draw', 'default', 'hold', 'reveal'],
  'layers-minus': ['draw', 'default', 'hold', 'reveal'],
  'layers-plus': ['draw', 'default', 'hold', 'reveal'],
  'layout-dashboard': ['draw', 'default', 'focus', 'swap', 'alert', 'assemble', 'reveal'],
  'layout-freeform': ['draw', 'default', 'shake', 'shuffle', 'reveal'],
  'layout-grid': ['draw', 'default', 'alert', 'assemble', 'reveal'],
  'layout-list': ['draw', 'default', 'flash', 'read', 'reveal'],
  'layout-panel-left': ['draw', 'default', 'focus', 'alert', 'reveal'],
  'layout-panel-top': ['draw', 'default', 'focus', 'alert', 'reveal'],
  'layout-template': ['draw', 'default', 'focus', 'select', 'alert', 'reveal'],
  leaf: ['draw', 'default', 'hold', 'reveal'],
  'leafy-green': ['draw', 'default', 'hold', 'reveal'],
  lectern: ['draw', 'default', 'hold', 'reveal'],
  'lens-concave': ['draw', 'default', 'hold', 'reveal'],
  'lens-convex': ['draw', 'default', 'hold', 'reveal'],
  library: ['draw', 'default', 'reveal'],
  'library-big': ['draw', 'default', 'reveal'],
  'life-buoy': ['draw', 'default', 'hold', 'reveal'],
  ligature: ['draw', 'default', 'reveal'],
  lightbulb: ['draw', 'default', 'alert', 'spark', 'reveal'],
  'lightbulb-off': ['draw', 'default', 'strike', 'reveal'],
  'line-dot-right-horizontal': ['draw', 'default', 'hold', 'reveal'],
  'line-squiggle': ['draw', 'default', 'hold', 'reveal'],
  'line-style': ['draw', 'default', 'hold', 'reveal'],
  link: ['draw', 'default', 'reveal'],
  'link-2': ['draw', 'default', 'reveal'],
  'link-2-off': ['draw', 'default', 'strike', 'reveal'],
  list: ['draw', 'default', 'reveal'],
  'list-check': ['draw', 'default', 'reveal'],
  'list-checks': ['draw', 'default', 'mark', 'reveal'],
  'list-chevrons-down-up': ['draw', 'default', 'hold', 'reveal'],
  'list-chevrons-up-down': ['draw', 'default', 'hold', 'nudge', 'reveal'],
  'list-collapse': ['draw', 'default', 'hold', 'reveal'],
  'list-end': ['draw', 'default', 'hold', 'flip', 'reveal'],
  'list-filter': ['draw', 'default', 'reveal'],
  'list-filter-plus': ['draw', 'default', 'reveal'],
  'list-indent-decrease': ['draw', 'default', 'reveal'],
  'list-indent-increase': ['draw', 'default', 'reveal'],
  'list-minus': ['draw', 'default', 'reveal'],
  'list-music': ['draw', 'default', 'reveal'],
  'list-ordered': ['draw', 'default', 'reveal'],
  'list-plus': ['draw', 'default', 'reveal'],
  'list-restart': ['draw', 'default', 'reveal'],
  'list-sort-ascending': ['draw', 'default', 'flip', 'reveal'],
  'list-sort-descending': ['draw', 'default', 'flip', 'reveal'],
  'list-start': ['draw', 'default', 'hold', 'flip', 'reveal'],
  'list-todo': ['draw', 'default', 'reveal'],
  'list-tree': ['draw', 'default', 'reveal'],
  'list-video': ['draw', 'default', 'reveal'],
  'list-x': ['draw', 'default', 'reveal'],
  loader: ['draw', 'default', 'reveal'],
  'loader-circle': ['draw', 'default', 'reveal'],
  'loader-pinwheel': ['draw', 'default', 'reveal'],
  locate: ['draw', 'default', 'assemble', 'reveal'],
  'locate-fixed': ['draw', 'default', 'assemble', 'reveal'],
  'locate-off': ['draw', 'default', 'strike', 'reveal'],
  lock: ['draw', 'default', 'reveal'],
  'lock-keyhole': ['draw', 'default', 'reveal'],
  'lock-keyhole-open': ['draw', 'default', 'reveal'],
  'lock-open': ['draw', 'default', 'reveal'],
  'log-in': ['draw', 'default', 'assemble', 'nudge', 'reveal'],
  'log-out': ['draw', 'default', 'nudge', 'hold', 'assemble', 'reveal'],
  logs: ['draw', 'default', 'hold', 'reveal'],
  lollipop: ['draw', 'default', 'hold', 'reveal'],
  luggage: ['draw', 'default', 'hold', 'reveal'],
  magnet: ['draw', 'default', 'hold', 'reveal'],
  mail: ['draw', 'default', 'pulse', 'reveal'],
  'mail-badge': ['draw', 'default', 'hold', 'reveal'],
  'mail-check': ['draw', 'default', 'hold', 'pulse', 'reveal'],
  'mail-minus': ['draw', 'default', 'hold', 'reveal'],
  'mail-open': ['draw', 'default', 'reveal'],
  'mail-plus': ['draw', 'default', 'hold', 'reveal'],
  'mail-question-mark': ['draw', 'default', 'hold', 'reveal'],
  'mail-search': ['draw', 'default', 'hold', 'reveal'],
  'mail-warning': ['draw', 'default', 'hold', 'reveal'],
  'mail-x': ['draw', 'default', 'hold', 'reveal'],
  mailbox: ['draw', 'default', 'hold', 'bounce', 'reveal'],
  mails: ['draw', 'default', 'hold', 'reveal'],
  map: ['draw', 'default', 'reveal'],
  'map-minus': ['draw', 'default', 'reveal'],
  'map-pin': ['draw', 'default', 'pulse', 'locate', 'reveal'],
  'map-pin-check': ['draw', 'default', 'shake', 'mark', 'reveal'],
  'map-pin-check-inside': ['draw', 'default', 'mark', 'reveal'],
  'map-pin-house': ['draw', 'default', 'reveal'],
  'map-pin-minus': ['draw', 'default', 'reveal'],
  'map-pin-minus-inside': ['draw', 'default', 'reveal'],
  'map-pin-off': ['draw', 'default', 'strike', 'reveal'],
  'map-pin-pen': ['draw', 'default', 'reveal'],
  'map-pin-plus': ['draw', 'default', 'reveal'],
  'map-pin-plus-inside': ['draw', 'default', 'reveal'],
  'map-pin-search': ['draw', 'default', 'nudge', 'scan', 'reveal'],
  'map-pin-x': ['draw', 'default', 'shake', 'deny', 'reveal'],
  'map-pin-x-inside': ['draw', 'default', 'reveal'],
  'map-pinned': ['draw', 'default', 'reveal'],
  'map-plus': ['draw', 'default', 'reveal'],
  mars: ['draw', 'default', 'hold', 'reveal'],
  'mars-stroke': ['draw', 'default', 'hold', 'reveal'],
  martini: ['draw', 'default', 'hold', 'reveal'],
  maximize: ['draw', 'default', 'reveal'],
  'maximize-2': ['draw', 'default', 'reveal'],
  medal: ['draw', 'default', 'hold', 'reveal'],
  megaphone: ['draw', 'default', 'reveal'],
  'megaphone-off': ['draw', 'default', 'strike', 'reveal'],
  'memory-stick': ['draw', 'default', 'hold', 'reveal'],
  menu: ['draw', 'default', 'reveal'],
  merge: ['draw', 'default', 'hold', 'reveal'],
  'message-circle': ['draw', 'default', 'hold', 'reveal'],
  'message-circle-check': ['draw', 'default', 'hold', 'reveal'],
  'message-circle-code': ['draw', 'default', 'hold', 'reveal'],
  'message-circle-dashed': ['draw', 'default', 'hold', 'reveal'],
  'message-circle-heart': ['draw', 'default', 'hold', 'reveal'],
  'message-circle-more': ['draw', 'default', 'hold', 'reveal'],
  'message-circle-off': ['draw', 'default', 'hold', 'strike', 'reveal'],
  'message-circle-plus': ['draw', 'default', 'hold', 'reveal'],
  'message-circle-question-mark': ['draw', 'default', 'hold', 'reveal'],
  'message-circle-reply': ['draw', 'default', 'hold', 'reveal'],
  'message-circle-warning': ['draw', 'default', 'hold', 'reveal'],
  'message-circle-x': ['draw', 'default', 'hold', 'reveal'],
  'message-square': ['draw', 'default', 'hold', 'reveal'],
  'message-square-check': ['draw', 'default', 'hold', 'reveal'],
  'message-square-code': ['draw', 'default', 'hold', 'reveal'],
  'message-square-dashed': ['draw', 'default', 'hold', 'reveal'],
  'message-square-diff': ['draw', 'default', 'hold', 'reveal'],
  'message-square-dot': ['draw', 'default', 'hold', 'reveal'],
  'message-square-heart': ['draw', 'default', 'hold', 'reveal'],
  'message-square-lock': ['draw', 'default', 'hold', 'reveal'],
  'message-square-more': ['draw', 'default', 'hold', 'reveal'],
  'message-square-off': ['draw', 'default', 'hold', 'strike', 'reveal'],
  'message-square-plus': ['draw', 'default', 'hold', 'reveal'],
  'message-square-quote': ['draw', 'default', 'hold', 'reveal'],
  'message-square-reply': ['draw', 'default', 'hold', 'reveal'],
  'message-square-share': ['draw', 'default', 'hold', 'reveal'],
  'message-square-text': ['draw', 'default', 'hold', 'reveal'],
  'message-square-warning': ['draw', 'default', 'hold', 'reveal'],
  'message-square-x': ['draw', 'default', 'hold', 'reveal'],
  'messages-square': ['draw', 'default', 'hold', 'reveal'],
  metronome: ['draw', 'default', 'hold', 'reveal'],
  mic: ['draw', 'default', 'reveal'],
  'mic-audio-lines': ['draw', 'default', 'reveal'],
  'mic-off': ['draw', 'default', 'strike', 'reveal'],
  'mic-signal': ['draw', 'default', 'reveal'],
  'mic-vocal': ['draw', 'default', 'reveal'],
  microchip: ['draw', 'default', 'hold', 'reveal'],
  microscope: ['draw', 'default', 'hold', 'reveal'],
  microwave: ['draw', 'default', 'hold', 'reveal'],
  milestone: ['draw', 'default', 'hold', 'reveal'],
  milk: ['draw', 'default', 'reveal'],
  'milk-off': ['draw', 'default', 'strike', 'reveal'],
  minimize: ['draw', 'default', 'reveal'],
  'minimize-2': ['draw', 'default', 'reveal'],
  minus: ['draw', 'default', 'reveal'],
  'mirror-rectangular': ['draw', 'default', 'hold', 'reveal'],
  'mirror-round': ['draw', 'default', 'hold', 'reveal'],
  monitor: ['draw', 'default', 'nudge', 'reveal'],
  'monitor-check': ['draw', 'default', 'nudge', 'reveal'],
  'monitor-cloud': ['draw', 'default', 'nudge', 'reveal'],
  'monitor-cog': ['draw', 'default', 'nudge', 'reveal'],
  'monitor-dot': ['draw', 'default', 'nudge', 'reveal'],
  'monitor-down': ['draw', 'default', 'nudge', 'reveal'],
  'monitor-off': ['draw', 'default', 'strike', 'nudge', 'reveal'],
  'monitor-pause': ['draw', 'default', 'nudge', 'reveal'],
  'monitor-play': ['draw', 'default', 'nudge', 'reveal'],
  'monitor-smartphone': ['draw', 'default', 'nudge', 'reveal'],
  'monitor-speaker': ['draw', 'default', 'nudge', 'reveal'],
  'monitor-stop': ['draw', 'default', 'nudge', 'reveal'],
  'monitor-up': ['draw', 'default', 'nudge', 'reveal'],
  'monitor-x': ['draw', 'default', 'nudge', 'reveal'],
  moon: ['draw', 'default', 'reveal'],
  'moon-star': ['draw', 'default', 'reveal'],
  mosque: ['draw', 'default', 'hold', 'reveal'],
  motorbike: ['draw', 'default', 'hold', 'reveal'],
  mountain: ['draw', 'default', 'reveal'],
  'mountain-snow': ['draw', 'default', 'reveal'],
  mouse: ['draw', 'default', 'reveal'],
  'mouse-left': ['draw', 'default', 'wander', 'reveal'],
  'mouse-off': ['draw', 'default', 'alert', 'strike', 'reveal'],
  'mouse-pointer': ['draw', 'default', 'wander', 'nudge', 'reveal'],
  'mouse-pointer-2': ['draw', 'default', 'wander', 'nudge', 'reveal'],
  'mouse-pointer-2-off': ['draw', 'default', 'strike', 'reveal'],
  'mouse-pointer-ban': ['draw', 'default', 'wander', 'reveal'],
  'mouse-pointer-click': ['draw', 'default', 'reveal'],
  'mouse-right': ['draw', 'default', 'wander', 'reveal'],
  move: ['draw', 'default', 'expand', 'collapse', 'reveal'],
  'move-3d': ['draw', 'default', 'reveal'],
  'move-diagonal': ['draw', 'default', 'reveal'],
  'move-diagonal-2': ['draw', 'default', 'reveal'],
  'move-down': ['draw', 'default', 'reveal'],
  'move-down-left': ['draw', 'default', 'reveal'],
  'move-down-right': ['draw', 'default', 'reveal'],
  'move-horizontal': ['draw', 'default', 'reveal'],
  'move-left': ['draw', 'default', 'reveal'],
  'move-right': ['draw', 'default', 'reveal'],
  'move-up': ['draw', 'default', 'reveal'],
  'move-up-left': ['draw', 'default', 'reveal'],
  'move-up-right': ['draw', 'default', 'reveal'],
  'move-vertical': ['draw', 'default', 'reveal'],
  music: ['draw', 'default', 'reveal'],
  'music-2': ['draw', 'default', 'reveal'],
  'music-3': ['draw', 'default', 'reveal'],
  'music-4': ['draw', 'default', 'reveal'],
  navigation: ['draw', 'default', 'reveal'],
  'navigation-2': ['draw', 'default', 'reveal'],
  'navigation-2-off': ['draw', 'default', 'strike', 'reveal'],
  'navigation-off': ['draw', 'default', 'strike', 'reveal'],
  network: ['draw', 'default', 'reveal'],
  newspaper: ['draw', 'default', 'hold', 'reveal'],
  nfc: ['draw', 'default', 'reveal'],
  'non-binary': ['draw', 'default', 'hold', 'reveal'],
  notebook: ['draw', 'default', 'reveal'],
  'notebook-pen': ['draw', 'default', 'pulse', 'reveal'],
  'notebook-tabs': ['draw', 'default', 'pulse', 'reveal'],
  'notebook-text': ['draw', 'default', 'pulse', 'reveal'],
  'notepad-text': ['draw', 'default', 'hold', 'reveal'],
  'notepad-text-dashed': ['draw', 'default', 'hold', 'reveal'],
  nut: ['draw', 'default', 'reveal'],
  'nut-off': ['draw', 'default', 'strike', 'reveal'],
  octagon: ['draw', 'default', 'reveal'],
  'octagon-alert': ['draw', 'default', 'reveal'],
  'octagon-minus': ['draw', 'default', 'reveal'],
  'octagon-pause': ['draw', 'default', 'reveal'],
  'octagon-x': ['draw', 'default', 'reveal'],
  omega: ['draw', 'default', 'reveal'],
  option: ['draw', 'default', 'hold', 'reveal'],
  orbit: ['draw', 'default', 'reveal'],
  origami: ['draw', 'default', 'hold', 'reveal'],
  package: ['draw', 'default', 'reveal'],
  'package-2': ['draw', 'default', 'reveal'],
  'package-check': ['draw', 'default', 'drop', 'mark', 'reveal'],
  'package-minus': ['draw', 'default', 'drop', 'reveal'],
  'package-open': ['draw', 'default', 'bounce', 'wide', 'reveal'],
  'package-plus': ['draw', 'default', 'drop', 'reveal'],
  'package-search': ['draw', 'default', 'reveal'],
  'package-x': ['draw', 'default', 'drop', 'reveal'],
  'paint-bucket': ['draw', 'default', 'hold', 'reveal'],
  'paint-roller': ['draw', 'default', 'hold', 'reveal'],
  paintbrush: ['draw', 'default', 'reveal'],
  'paintbrush-vertical': ['draw', 'default', 'reveal'],
  palette: ['draw', 'default', 'pulse', 'reveal'],
  panda: ['draw', 'default', 'hold', 'reveal'],
  'panel-bottom': ['draw', 'default', 'reveal'],
  'panel-bottom-close': ['draw', 'default', 'active', 'reveal'],
  'panel-bottom-dashed': ['draw', 'default', 'active', 'reveal'],
  'panel-bottom-open': ['draw', 'default', 'active', 'reveal'],
  'panel-left': ['draw', 'default', 'reveal'],
  'panel-left-close': ['draw', 'default', 'active', 'reveal'],
  'panel-left-dashed': ['draw', 'default', 'active', 'reveal'],
  'panel-left-open': ['draw', 'default', 'active', 'reveal'],
  'panel-left-right-dashed': ['draw', 'default', 'active', 'reveal'],
  'panel-right': ['draw', 'default', 'reveal'],
  'panel-right-close': ['draw', 'default', 'active', 'reveal'],
  'panel-right-dashed': ['draw', 'default', 'active', 'reveal'],
  'panel-right-open': ['draw', 'default', 'active', 'reveal'],
  'panel-top': ['draw', 'default', 'reveal'],
  'panel-top-bottom-dashed': ['draw', 'default', 'active', 'reveal'],
  'panel-top-close': ['draw', 'default', 'active', 'reveal'],
  'panel-top-dashed': ['draw', 'default', 'active', 'reveal'],
  'panel-top-open': ['draw', 'default', 'active', 'reveal'],
  'panels-left-bottom': ['draw', 'default', 'reveal'],
  'panels-right-bottom': ['draw', 'default', 'reveal'],
  'panels-top-left': ['draw', 'default', 'reveal'],
  'paper-bag': ['draw', 'default', 'hold', 'reveal'],
  paperclip: ['draw', 'default', 'pulse', 'reveal'],
  parasol: ['draw', 'default', 'hold', 'reveal'],
  parentheses: ['draw', 'default', 'hold', 'reveal'],
  'parking-meter': ['draw', 'default', 'hold', 'reveal'],
  'party-popper': ['draw', 'default', 'hold', 'reveal'],
  pause: ['draw', 'default', 'reveal'],
  'paw-print': ['draw', 'default', 'hold', 'reveal'],
  'pc-case': ['draw', 'default', 'hold', 'reveal'],
  pen: ['draw', 'default', 'write', 'nudge', 'reveal'],
  'pen-line': ['draw', 'default', 'write', 'nudge', 'reveal'],
  'pen-off': ['draw', 'default', 'strike', 'reveal'],
  'pen-tool': ['draw', 'default', 'reveal'],
  pencil: ['draw', 'default', 'write', 'nudge', 'reveal'],
  'pencil-line': ['draw', 'default', 'reveal'],
  'pencil-off': ['draw', 'default', 'strike', 'reveal'],
  'pencil-ruler': ['draw', 'default', 'reveal'],
  'pencil-sparkles': ['draw', 'default', 'reveal'],
  pentagon: ['draw', 'default', 'hold', 'reveal'],
  percent: ['draw', 'default', 'reveal'],
  'person-standing': ['draw', 'default', 'hold', 'reveal'],
  phi: ['draw', 'default', 'reveal'],
  'philippine-peso': ['draw', 'default', 'reveal'],
  phone: ['draw', 'default', 'ring', 'reveal'],
  'phone-call': ['draw', 'default', 'ring', 'reveal'],
  'phone-forwarded': ['draw', 'default', 'ring', 'reveal'],
  'phone-incoming': ['draw', 'default', 'ring', 'reveal'],
  'phone-missed': ['draw', 'default', 'reveal'],
  'phone-off': ['draw', 'default', 'strike', 'reveal'],
  'phone-outgoing': ['draw', 'default', 'reveal'],
  pi: ['draw', 'default', 'reveal'],
  piano: ['draw', 'default', 'hold', 'reveal'],
  pickaxe: ['draw', 'default', 'reveal'],
  'picture-in-picture': ['draw', 'default', 'hold', 'reveal'],
  'picture-in-picture-2': ['draw', 'default', 'hold', 'reveal'],
  'piggy-bank': ['draw', 'default', 'hold', 'reveal'],
  pilcrow: ['draw', 'default', 'reveal'],
  'pilcrow-left': ['draw', 'default', 'reveal'],
  'pilcrow-right': ['draw', 'default', 'reveal'],
  pill: ['draw', 'default', 'hold', 'reveal'],
  'pill-bottle': ['draw', 'default', 'hold', 'reveal'],
  pin: ['draw', 'default', 'reveal'],
  'pin-off': ['draw', 'default', 'strike', 'reveal'],
  pipette: ['draw', 'default', 'hold', 'reveal'],
  pizza: ['draw', 'default', 'hold', 'reveal'],
  plane: ['draw', 'default', 'reveal'],
  'plane-landing': ['draw', 'default', 'reveal'],
  'plane-takeoff': ['draw', 'default', 'reveal'],
  play: ['draw', 'default', 'nudge', 'next', 'active', 'reveal'],
  'play-off': ['draw', 'default', 'strike', 'reveal'],
  plug: ['draw', 'default', 'hold', 'reveal'],
  'plug-2': ['draw', 'default', 'hold', 'reveal'],
  'plug-zap': ['draw', 'default', 'hold', 'reveal'],
  plus: ['draw', 'default', 'turn', 'reveal'],
  'pocket-knife': ['draw', 'default', 'hold', 'reveal'],
  podium: ['draw', 'default', 'hold', 'reveal'],
  pointer: ['draw', 'default', 'reveal'],
  'pointer-off': ['draw', 'default', 'strike', 'reveal'],
  popcorn: ['draw', 'default', 'hold', 'reveal'],
  popsicle: ['draw', 'default', 'hold', 'reveal'],
  'pound-sterling': ['draw', 'default', 'reveal'],
  power: ['draw', 'default', 'reveal'],
  'power-off': ['draw', 'default', 'strike', 'reveal'],
  presentation: ['draw', 'default', 'hold', 'reveal'],
  printer: ['draw', 'default', 'reveal'],
  'printer-check': ['draw', 'default', 'reveal'],
  'printer-x': ['draw', 'default', 'reveal'],
  projector: ['draw', 'default', 'hold', 'reveal'],
  proportions: ['draw', 'default', 'hold', 'reveal'],
  puzzle: ['draw', 'default', 'hold', 'reveal'],
  pyramid: ['draw', 'default', 'hold', 'reveal'],
  'qr-code': ['draw', 'default', 'scan', 'reveal'],
  quote: ['draw', 'default', 'reveal'],
  rabbit: ['draw', 'default', 'idle', 'reveal'],
  radar: ['draw', 'default', 'reveal'],
  radiation: ['draw', 'default', 'hold', 'reveal'],
  radical: ['draw', 'default', 'reveal'],
  radio: ['draw', 'default', 'pulse', 'reveal'],
  'radio-off': ['draw', 'default', 'strike', 'reveal'],
  'radio-receiver': ['draw', 'default', 'reveal'],
  'radio-tower': ['draw', 'default', 'reveal'],
  radius: ['draw', 'default', 'hold', 'reveal'],
  rainbow: ['draw', 'default', 'reveal'],
  rat: ['draw', 'default', 'hold', 'reveal'],
  ratio: ['draw', 'default', 'hold', 'reveal'],
  receipt: ['draw', 'default', 'pulse', 'reveal'],
  'receipt-cent': ['draw', 'default', 'pulse', 'reveal'],
  'receipt-euro': ['draw', 'default', 'pulse', 'reveal'],
  'receipt-indian-rupee': ['draw', 'default', 'pulse', 'reveal'],
  'receipt-japanese-yen': ['draw', 'default', 'pulse', 'reveal'],
  'receipt-pound-sterling': ['draw', 'default', 'pulse', 'reveal'],
  'receipt-russian-ruble': ['draw', 'default', 'pulse', 'reveal'],
  'receipt-swiss-franc': ['draw', 'default', 'pulse', 'reveal'],
  'receipt-text': ['draw', 'default', 'pulse', 'reveal'],
  'receipt-turkish-lira': ['draw', 'default', 'pulse', 'reveal'],
  'rectangle-circle': ['draw', 'default', 'reveal'],
  'rectangle-ellipsis': ['draw', 'default', 'reveal'],
  'rectangle-goggles': ['draw', 'default', 'reveal'],
  'rectangle-horizontal': ['draw', 'default', 'reveal'],
  'rectangle-vertical': ['draw', 'default', 'reveal'],
  recycle: ['draw', 'default', 'hold', 'reveal'],
  redo: ['draw', 'default', 'flip', 'reveal'],
  'redo-2': ['draw', 'default', 'flip', 'reveal'],
  'redo-dot': ['draw', 'default', 'reveal'],
  'refresh-ccw': ['draw', 'default', 'flip', 'reveal'],
  'refresh-ccw-dot': ['draw', 'default', 'reveal'],
  'refresh-cw': ['draw', 'default', 'spin', 'rotate', 'active', 'flip', 'reveal'],
  'refresh-cw-off': ['draw', 'default', 'strike', 'reveal'],
  refrigerator: ['draw', 'default', 'hold', 'reveal'],
  regex: ['draw', 'default', 'reveal'],
  'remove-formatting': ['draw', 'default', 'reveal'],
  repeat: ['draw', 'default', 'nudge', 'reveal'],
  'repeat-1': ['draw', 'default', 'reveal'],
  'repeat-2': ['draw', 'default', 'reveal'],
  'repeat-off': ['draw', 'default', 'strike', 'reveal'],
  replace: ['draw', 'default', 'reveal'],
  'replace-all': ['draw', 'default', 'reveal'],
  reply: ['draw', 'default', 'flip', 'reveal'],
  'reply-all': ['draw', 'default', 'nudge', 'reveal'],
  rewind: ['draw', 'default', 'flip', 'reveal'],
  ribbon: ['draw', 'default', 'hold', 'reveal'],
  road: ['draw', 'default', 'hold', 'reveal'],
  rocket: ['draw', 'default', 'hold', 'bounce', 'reveal'],
  'rocking-chair': ['draw', 'default', 'reveal'],
  'roller-coaster': ['draw', 'default', 'hold', 'reveal'],
  rose: ['draw', 'default', 'hold', 'reveal'],
  'rotate-3d': ['draw', 'default', 'reveal'],
  'rotate-ccw': ['draw', 'default', 'active', 'flip', 'reveal'],
  'rotate-ccw-clock': ['draw', 'default', 'reveal'],
  'rotate-ccw-key': ['draw', 'default', 'reveal'],
  'rotate-ccw-square': ['draw', 'default', 'reveal'],
  'rotate-cw': ['draw', 'default', 'active', 'flip', 'reveal'],
  'rotate-cw-fading-clock': ['draw', 'default', 'reveal'],
  'rotate-cw-square': ['draw', 'default', 'reveal'],
  route: ['draw', 'default', 'assemble', 'reveal'],
  'route-off': ['draw', 'default', 'strike', 'reveal'],
  router: ['draw', 'default', 'reveal'],
  'rows-2': ['draw', 'default', 'reveal'],
  'rows-3': ['draw', 'default', 'reveal'],
  'rows-4': ['draw', 'default', 'reveal'],
  rss: ['draw', 'default', 'reveal'],
  ruler: ['draw', 'default', 'hold', 'reveal'],
  'ruler-dimension-line': ['draw', 'default', 'hold', 'reveal'],
  'russian-ruble': ['draw', 'default', 'reveal'],
  sailboat: ['draw', 'default', 'hold', 'reveal'],
  salad: ['draw', 'default', 'hold', 'reveal'],
  sandwich: ['draw', 'default', 'hold', 'reveal'],
  satellite: ['draw', 'default', 'hold', 'reveal'],
  'satellite-dish': ['draw', 'default', 'hold', 'reveal'],
  'saudi-riyal': ['draw', 'default', 'reveal'],
  save: ['draw', 'default', 'reveal'],
  'save-all': ['draw', 'default', 'pulse', 'stack', 'reveal'],
  'save-check': ['draw', 'default', 'pop', 'reveal'],
  'save-off': ['draw', 'default', 'quick', 'alert', 'strike', 'reveal'],
  'save-pen': ['draw', 'default', 'pop', 'reveal'],
  'save-plus': ['draw', 'default', 'pop', 'reveal'],
  scale: ['draw', 'default', 'hold', 'reveal'],
  'scale-3d': ['draw', 'default', 'hold', 'reveal'],
  scaling: ['draw', 'default', 'hold', 'reveal'],
  scan: ['draw', 'default', 'hold', 'reveal'],
  'scan-barcode': ['draw', 'default', 'hold', 'reveal'],
  'scan-box': ['draw', 'default', 'hold', 'reveal'],
  'scan-eye': ['draw', 'default', 'hold', 'reveal'],
  'scan-face': ['draw', 'default', 'hold', 'idle', 'reveal'],
  'scan-heart': ['draw', 'default', 'hold', 'reveal'],
  'scan-line': ['draw', 'default', 'hold', 'reveal'],
  'scan-qr-code': ['draw', 'default', 'hold', 'reveal'],
  'scan-search': ['draw', 'default', 'hold', 'reveal'],
  'scan-square': ['draw', 'default', 'hold', 'reveal'],
  'scan-text': ['draw', 'default', 'hold', 'reveal'],
  school: ['draw', 'default', 'hold', 'reveal'],
  scissors: ['draw', 'default', 'reveal'],
  'scissors-line-dashed': ['draw', 'default', 'reveal'],
  scooter: ['draw', 'default', 'hold', 'reveal'],
  'screen-share': ['draw', 'default', 'reveal'],
  'screen-share-off': ['draw', 'default', 'reveal'],
  scroll: ['draw', 'default', 'reveal'],
  'scroll-text': ['draw', 'default', 'reveal'],
  search: ['draw', 'default', 'find', 'nudge', 'reveal'],
  'search-alert': ['draw', 'default', 'reveal'],
  'search-check': ['draw', 'default', 'assemble', 'reveal'],
  'search-code': ['draw', 'default', 'reveal'],
  'search-slash': ['draw', 'default', 'assemble', 'reveal'],
  'search-x': ['draw', 'default', 'assemble', 'reveal'],
  section: ['draw', 'default', 'hold', 'reveal'],
  send: ['draw', 'default', 'reveal'],
  'send-horizontal': ['draw', 'default', 'reveal'],
  'send-to-back': ['draw', 'default', 'reveal'],
  'separator-horizontal': ['draw', 'default', 'reveal'],
  'separator-vertical': ['draw', 'default', 'reveal'],
  server: ['draw', 'default', 'reveal'],
  'server-cog': ['draw', 'default', 'spin', 'reveal'],
  'server-crash': ['draw', 'default', 'shake', 'shock', 'reveal'],
  'server-off': ['draw', 'default', 'quick', 'alert', 'strike', 'reveal'],
  'server-plus': ['draw', 'default', 'alert', 'reveal'],
  settings: ['draw', 'default', 'spin', 'rotate', 'active', 'reveal'],
  'settings-2': ['draw', 'default', 'reveal'],
  shapes: ['draw', 'default', 'hold', 'reveal'],
  share: ['draw', 'default', 'reveal'],
  'share-2': ['draw', 'default', 'reveal'],
  sheet: ['draw', 'default', 'hold', 'reveal'],
  shell: ['draw', 'default', 'hold', 'reveal'],
  'shelving-unit': ['draw', 'default', 'hold', 'reveal'],
  shield: ['draw', 'default', 'pulse', 'reveal'],
  'shield-alert': ['draw', 'default', 'alert', 'reveal'],
  'shield-ban': ['draw', 'default', 'reveal'],
  'shield-check': ['draw', 'default', 'mark', 'reveal'],
  'shield-cog': ['draw', 'default', 'reveal'],
  'shield-cog-corner': ['draw', 'default', 'reveal'],
  'shield-ellipsis': ['draw', 'default', 'reveal'],
  'shield-half': ['draw', 'default', 'reveal'],
  'shield-keyhole': ['draw', 'default', 'reveal'],
  'shield-lock': ['draw', 'default', 'reveal'],
  'shield-minus': ['draw', 'default', 'reveal'],
  'shield-off': ['draw', 'default', 'alert', 'strike', 'reveal'],
  'shield-plus': ['draw', 'default', 'mark', 'reveal'],
  'shield-question-mark': ['draw', 'default', 'reveal'],
  'shield-user': ['draw', 'default', 'reveal'],
  'shield-x': ['draw', 'default', 'reveal'],
  ship: ['draw', 'default', 'reveal'],
  'ship-wheel': ['draw', 'default', 'reveal'],
  shirt: ['draw', 'default', 'reveal'],
  'shopping-bag': ['draw', 'default', 'bounce', 'reveal'],
  'shopping-basket': ['draw', 'default', 'reveal'],
  'shopping-cart': ['draw', 'default', 'pulse', 'bounce', 'reveal'],
  shovel: ['draw', 'default', 'reveal'],
  'shower-head': ['draw', 'default', 'hold', 'reveal'],
  shredder: ['draw', 'default', 'hold', 'reveal'],
  shrimp: ['draw', 'default', 'hold', 'reveal'],
  shrink: ['draw', 'default', 'reveal'],
  shrub: ['draw', 'default', 'hold', 'reveal'],
  shuffle: ['draw', 'default', 'nudge', 'reveal'],
  sigma: ['draw', 'default', 'reveal'],
  signal: ['draw', 'default', 'cascade', 'reveal'],
  'signal-high': ['draw', 'default', 'cascade', 'reveal'],
  'signal-low': ['draw', 'default', 'cascade', 'reveal'],
  'signal-medium': ['draw', 'default', 'cascade', 'reveal'],
  'signal-zero': ['draw', 'default', 'cascade', 'reveal'],
  signature: ['draw', 'default', 'reveal'],
  signpost: ['draw', 'default', 'hold', 'reveal'],
  'signpost-big': ['draw', 'default', 'hold', 'reveal'],
  siren: ['draw', 'default', 'hold', 'reveal'],
  'skip-back': ['draw', 'default', 'flip', 'reveal'],
  'skip-forward': ['draw', 'default', 'flip', 'reveal'],
  skull: ['draw', 'default', 'hold', 'reveal'],
  slash: ['draw', 'default', 'hold', 'reveal'],
  slice: ['draw', 'default', 'hold', 'reveal'],
  'sliders-horizontal': ['draw', 'default', 'nudge', 'reveal'],
  'sliders-vertical': ['draw', 'default', 'reveal'],
  smartphone: ['draw', 'default', 'ring', 'reveal'],
  'smartphone-charging': ['draw', 'default', 'reveal'],
  'smartphone-nfc': ['draw', 'default', 'reveal'],
  snail: ['draw', 'default', 'hold', 'reveal'],
  snowflake: ['draw', 'default', 'reveal'],
  'soap-dispenser-droplet': ['draw', 'default', 'hold', 'reveal'],
  sofa: ['draw', 'default', 'hold', 'reveal'],
  'solar-panel': ['draw', 'default', 'hold', 'reveal'],
  soup: ['draw', 'default', 'hold', 'reveal'],
  space: ['draw', 'default', 'hold', 'reveal'],
  spade: ['draw', 'default', 'hold', 'reveal'],
  sparkle: ['draw', 'default', 'reveal'],
  sparkles: ['draw', 'default', 'twinkle', 'reveal'],
  speaker: ['draw', 'default', 'hold', 'pulse', 'reveal'],
  speech: ['draw', 'default', 'reveal'],
  'spell-check': ['draw', 'default', 'reveal'],
  'spell-check-2': ['draw', 'default', 'reveal'],
  spline: ['draw', 'default', 'reveal'],
  'spline-pointer': ['draw', 'default', 'reveal'],
  split: ['draw', 'default', 'hold', 'reveal'],
  spool: ['draw', 'default', 'hold', 'reveal'],
  'sport-shoe': ['draw', 'default', 'hold', 'reveal'],
  spotlight: ['draw', 'default', 'hold', 'reveal'],
  'spray-can': ['draw', 'default', 'hold', 'reveal'],
  sprout: ['draw', 'default', 'hold', 'reveal'],
  square: ['draw', 'default', 'reveal'],
  'square-activity': ['draw', 'default', 'reveal'],
  'square-arrow-down': ['draw', 'default', 'reveal'],
  'square-arrow-down-left': ['draw', 'default', 'reveal'],
  'square-arrow-down-right': ['draw', 'default', 'reveal'],
  'square-arrow-left': ['draw', 'default', 'reveal'],
  'square-arrow-out-down-left': ['draw', 'default', 'reveal'],
  'square-arrow-out-down-right': ['draw', 'default', 'reveal'],
  'square-arrow-out-up-left': ['draw', 'default', 'reveal'],
  'square-arrow-out-up-right': ['draw', 'default', 'reveal'],
  'square-arrow-right': ['draw', 'default', 'reveal'],
  'square-arrow-right-enter': ['draw', 'default', 'reveal'],
  'square-arrow-right-exit': ['draw', 'default', 'reveal'],
  'square-arrow-up': ['draw', 'default', 'reveal'],
  'square-arrow-up-left': ['draw', 'default', 'reveal'],
  'square-arrow-up-right': ['draw', 'default', 'reveal'],
  'square-asterisk': ['draw', 'default', 'reveal'],
  'square-bottom-dashed-scissors': ['draw', 'default', 'reveal'],
  'square-centerline-dashed-horizontal': ['draw', 'default', 'reveal'],
  'square-centerline-dashed-vertical': ['draw', 'default', 'reveal'],
  'square-chart-gantt': ['draw', 'default', 'reveal'],
  'square-check': ['draw', 'default', 'reveal'],
  'square-check-big': ['draw', 'default', 'reveal'],
  'square-chevron-down': ['draw', 'default', 'reveal'],
  'square-chevron-left': ['draw', 'default', 'reveal'],
  'square-chevron-right': ['draw', 'default', 'reveal'],
  'square-chevron-up': ['draw', 'default', 'reveal'],
  'square-code': ['draw', 'default', 'reveal'],
  'square-dashed': ['draw', 'default', 'reveal'],
  'square-dashed-bottom': ['draw', 'default', 'reveal'],
  'square-dashed-bottom-code': ['draw', 'default', 'reveal'],
  'square-dashed-kanban': ['draw', 'default', 'reveal'],
  'square-dashed-mouse-pointer': ['draw', 'default', 'reveal'],
  'square-dashed-text': ['draw', 'default', 'reveal'],
  'square-dashed-top-solid': ['draw', 'default', 'reveal'],
  'square-divide': ['draw', 'default', 'reveal'],
  'square-dot': ['draw', 'default', 'reveal'],
  'square-equal': ['draw', 'default', 'reveal'],
  'square-function': ['draw', 'default', 'reveal'],
  'square-kanban': ['draw', 'default', 'reveal'],
  'square-library': ['draw', 'default', 'reveal'],
  'square-m': ['draw', 'default', 'reveal'],
  'square-menu': ['draw', 'default', 'reveal'],
  'square-minus': ['draw', 'default', 'reveal'],
  'square-mouse-pointer': ['draw', 'default', 'reveal'],
  'square-off': ['draw', 'default', 'alert', 'strike', 'reveal'],
  'square-parking': ['draw', 'default', 'reveal'],
  'square-parking-off': ['draw', 'default', 'strike', 'reveal'],
  'square-pause': ['draw', 'default', 'reveal'],
  'square-pen': ['draw', 'default', 'nudge', 'reveal'],
  'square-percent': ['draw', 'default', 'reveal'],
  'square-pi': ['draw', 'default', 'reveal'],
  'square-pilcrow': ['draw', 'default', 'reveal'],
  'square-play': ['draw', 'default', 'reveal'],
  'square-plus': ['draw', 'default', 'reveal'],
  'square-power': ['draw', 'default', 'reveal'],
  'square-radical': ['draw', 'default', 'reveal'],
  'square-round-corner': ['draw', 'default', 'reveal'],
  'square-scissors': ['draw', 'default', 'reveal'],
  'square-sigma': ['draw', 'default', 'reveal'],
  'square-slash': ['draw', 'default', 'reveal'],
  'square-split-horizontal': ['draw', 'default', 'reveal'],
  'square-split-vertical': ['draw', 'default', 'reveal'],
  'square-square': ['draw', 'default', 'reveal'],
  'square-stack': ['draw', 'default', 'reveal'],
  'square-star': ['draw', 'default', 'reveal'],
  'square-stop': ['draw', 'default', 'reveal'],
  'square-terminal': ['draw', 'default', 'reveal'],
  'square-user': ['draw', 'default', 'reveal'],
  'square-user-round': ['draw', 'default', 'reveal'],
  'square-x': ['draw', 'default', 'reveal'],
  'squares-exclude': ['draw', 'default', 'reveal'],
  'squares-intersect': ['draw', 'default', 'reveal'],
  'squares-subtract': ['draw', 'default', 'reveal'],
  'squares-unite': ['draw', 'default', 'reveal'],
  squircle: ['draw', 'default', 'reveal'],
  'squircle-dashed': ['draw', 'default', 'reveal'],
  squirrel: ['draw', 'default', 'hold', 'reveal'],
  stamp: ['draw', 'default', 'hold', 'reveal'],
  star: ['draw', 'default', 'twinkle', 'pulse', 'reveal'],
  'star-check': ['draw', 'default', 'twinkle', 'reveal'],
  'star-half': ['draw', 'default', 'twinkle', 'reveal'],
  'star-minus': ['draw', 'default', 'twinkle', 'reveal'],
  'star-off': ['draw', 'default', 'quick', 'alert', 'strike', 'reveal'],
  'star-plus': ['draw', 'default', 'twinkle', 'reveal'],
  'star-x': ['draw', 'default', 'twinkle', 'reveal'],
  'step-back': ['draw', 'default', 'flip', 'reveal'],
  'step-forward': ['draw', 'default', 'hold', 'flip', 'reveal'],
  stethoscope: ['draw', 'default', 'hold', 'reveal'],
  sticker: ['draw', 'default', 'hold', 'reveal'],
  'sticky-note': ['draw', 'default', 'flip', 'reveal'],
  'sticky-note-check': ['draw', 'default', 'flip', 'reveal'],
  'sticky-note-minus': ['draw', 'default', 'flip', 'reveal'],
  'sticky-note-off': ['draw', 'default', 'flip', 'strike', 'reveal'],
  'sticky-note-plus': ['draw', 'default', 'flip', 'reveal'],
  'sticky-note-x': ['draw', 'default', 'flip', 'reveal'],
  'sticky-notes': ['draw', 'default', 'reveal'],
  stone: ['draw', 'default', 'hold', 'reveal'],
  store: ['draw', 'default', 'hold', 'reveal'],
  'stretch-horizontal': ['draw', 'default', 'reveal'],
  'stretch-vertical': ['draw', 'default', 'reveal'],
  strikethrough: ['draw', 'default', 'reveal'],
  subscript: ['draw', 'default', 'reveal'],
  summary: ['draw', 'default', 'hold', 'reveal'],
  sun: ['draw', 'default', 'pulse', 'shine', 'reveal'],
  'sun-dim': ['draw', 'default', 'reveal'],
  'sun-medium': ['draw', 'default', 'reveal'],
  'sun-moon': ['draw', 'default', 'reveal'],
  'sun-snow': ['draw', 'default', 'reveal'],
  sunrise: ['draw', 'default', 'hold', 'reveal'],
  sunset: ['draw', 'default', 'hold', 'reveal'],
  superscript: ['draw', 'default', 'reveal'],
  'swatch-book': ['draw', 'default', 'hold', 'reveal'],
  'swiss-franc': ['draw', 'default', 'reveal'],
  'switch-camera': ['draw', 'default', 'hold', 'reveal'],
  sword: ['draw', 'default', 'reveal'],
  swords: ['draw', 'default', 'hold', 'reveal'],
  syringe: ['draw', 'default', 'hold', 'reveal'],
  table: ['draw', 'default', 'reveal'],
  'table-2': ['draw', 'default', 'reveal'],
  'table-cells-merge': ['draw', 'default', 'reveal'],
  'table-cells-split': ['draw', 'default', 'reveal'],
  'table-columns-split': ['draw', 'default', 'reveal'],
  'table-of-contents': ['draw', 'default', 'reveal'],
  'table-properties': ['draw', 'default', 'reveal'],
  'table-rows-split': ['draw', 'default', 'reveal'],
  tablet: ['draw', 'default', 'reveal'],
  'tablet-smartphone': ['draw', 'default', 'reveal'],
  tablets: ['draw', 'default', 'hold', 'reveal'],
  tag: ['draw', 'default', 'nudge', 'reveal'],
  'tag-plus': ['draw', 'default', 'reveal'],
  'tag-x': ['draw', 'default', 'reveal'],
  tags: ['draw', 'default', 'hold', 'reveal'],
  'tally-1': ['draw', 'default', 'count', 'reveal'],
  'tally-2': ['draw', 'default', 'count', 'reveal'],
  'tally-3': ['draw', 'default', 'count', 'reveal'],
  'tally-4': ['draw', 'default', 'count', 'reveal'],
  'tally-5': ['draw', 'default', 'count', 'reveal'],
  tangent: ['draw', 'default', 'hold', 'reveal'],
  target: ['draw', 'default', 'hold', 'reveal'],
  telescope: ['draw', 'default', 'reveal'],
  tent: ['draw', 'default', 'hold', 'reveal'],
  'tent-tree': ['draw', 'default', 'hold', 'reveal'],
  terminal: ['draw', 'default', 'reveal'],
  'test-tube': ['draw', 'default', 'hold', 'reveal'],
  'test-tube-diagonal': ['draw', 'default', 'hold', 'reveal'],
  'test-tubes': ['draw', 'default', 'hold', 'reveal'],
  'text-align-center': ['draw', 'default', 'reveal'],
  'text-align-end': ['draw', 'default', 'flip', 'reveal'],
  'text-align-justify': ['draw', 'default', 'reveal'],
  'text-align-start': ['draw', 'default', 'flip', 'reveal'],
  'text-cursor': ['draw', 'default', 'reveal'],
  'text-cursor-input': ['draw', 'default', 'reveal'],
  'text-initial': ['draw', 'default', 'reveal'],
  'text-quote': ['draw', 'default', 'reveal'],
  'text-search': ['draw', 'default', 'reveal'],
  'text-wrap': ['draw', 'default', 'cascade', 'reveal'],
  theater: ['draw', 'default', 'hold', 'reveal'],
  thermometer: ['draw', 'default', 'reveal'],
  'thermometer-snowflake': ['draw', 'default', 'reveal'],
  'thermometer-sun': ['draw', 'default', 'reveal'],
  'thumbs-down': ['draw', 'default', 'flip', 'reveal'],
  'thumbs-up': ['draw', 'default', 'flip', 'reveal'],
  ticket: ['draw', 'default', 'tear', 'reveal'],
  'ticket-check': ['draw', 'default', 'tear', 'mark', 'reveal'],
  'ticket-minus': ['draw', 'default', 'tear', 'reveal'],
  'ticket-percent': ['draw', 'default', 'tear', 'reveal'],
  'ticket-plus': ['draw', 'default', 'tear', 'reveal'],
  'ticket-slash': ['draw', 'default', 'tear', 'reveal'],
  'ticket-x': ['draw', 'default', 'tear', 'reveal'],
  tickets: ['draw', 'default', 'reveal'],
  'tickets-plane': ['draw', 'default', 'reveal'],
  timeline: ['draw', 'default', 'hold', 'reveal'],
  timer: ['draw', 'default', 'reveal'],
  'timer-off': ['draw', 'default', 'strike', 'reveal'],
  'timer-reset': ['draw', 'default', 'reveal'],
  'toggle-left': ['draw', 'default', 'reveal'],
  'toggle-right': ['draw', 'default', 'reveal'],
  toilet: ['draw', 'default', 'hold', 'reveal'],
  'tool-case': ['draw', 'default', 'hold', 'reveal'],
  toolbox: ['draw', 'default', 'hold', 'reveal'],
  tornado: ['draw', 'default', 'reveal'],
  torus: ['draw', 'default', 'hold', 'reveal'],
  touchpad: ['draw', 'default', 'reveal'],
  'touchpad-off': ['draw', 'default', 'strike', 'reveal'],
  'towel-rack': ['draw', 'default', 'hold', 'reveal'],
  'tower-control': ['draw', 'default', 'hold', 'reveal'],
  'toy-brick': ['draw', 'default', 'hold', 'reveal'],
  tractor: ['draw', 'default', 'hold', 'reveal'],
  'traffic-cone': ['draw', 'default', 'hold', 'reveal'],
  'train-front': ['draw', 'default', 'hold', 'reveal'],
  'train-front-tunnel': ['draw', 'default', 'hold', 'reveal'],
  'train-track': ['draw', 'default', 'hold', 'reveal'],
  'tram-front': ['draw', 'default', 'hold', 'reveal'],
  transgender: ['draw', 'default', 'hold', 'reveal'],
  trash: ['draw', 'default', 'active', 'reveal'],
  'trash-2': ['draw', 'default', 'active', 'spark', 'reveal'],
  'tree-deciduous': ['draw', 'default', 'hold', 'reveal'],
  'tree-palm': ['draw', 'default', 'hold', 'reveal'],
  'tree-pine': ['draw', 'default', 'hold', 'reveal'],
  trees: ['draw', 'default', 'hold', 'reveal'],
  'trending-down': ['draw', 'default', 'flip', 'reveal'],
  'trending-up': ['draw', 'default', 'flip', 'reveal'],
  'trending-up-down': ['draw', 'default', 'reveal'],
  triangle: ['draw', 'default', 'reveal'],
  'triangle-alert': ['draw', 'default', 'alert', 'reveal'],
  'triangle-dashed': ['draw', 'default', 'reveal'],
  'triangle-right': ['draw', 'default', 'reveal'],
  trophy: ['draw', 'default', 'hold', 'reveal'],
  truck: ['draw', 'default', 'reveal'],
  'truck-electric': ['draw', 'default', 'reveal'],
  'turkish-lira': ['draw', 'default', 'reveal'],
  turntable: ['draw', 'default', 'hold', 'reveal'],
  turtle: ['draw', 'default', 'hold', 'reveal'],
  tv: ['draw', 'default', 'pulse', 'reveal'],
  'tv-minimal': ['draw', 'default', 'reveal'],
  'tv-minimal-play': ['draw', 'default', 'reveal'],
  type: ['draw', 'default', 'reveal'],
  'type-outline': ['draw', 'default', 'reveal'],
  umbrella: ['draw', 'default', 'reveal'],
  'umbrella-off': ['draw', 'default', 'strike', 'reveal'],
  underline: ['draw', 'default', 'reveal'],
  undo: ['draw', 'default', 'flip', 'reveal'],
  'undo-2': ['draw', 'default', 'flip', 'reveal'],
  'undo-dot': ['draw', 'default', 'reveal'],
  'unfold-horizontal': ['draw', 'default', 'reveal'],
  'unfold-vertical': ['draw', 'default', 'reveal'],
  ungroup: ['draw', 'default', 'hold', 'reveal'],
  university: ['draw', 'default', 'hold', 'reveal'],
  unlink: ['draw', 'default', 'reveal'],
  'unlink-2': ['draw', 'default', 'reveal'],
  unplug: ['draw', 'default', 'reveal'],
  upload: ['draw', 'default', 'nudge', 'retract', 'active', 'reveal'],
  usb: ['draw', 'default', 'hold', 'reveal'],
  user: ['draw', 'default', 'alert', 'reveal'],
  'user-check': ['draw', 'default', 'mark', 'reveal'],
  'user-cog': ['draw', 'default', 'pulse', 'tune', 'active', 'reveal'],
  'user-key': ['draw', 'default', 'reveal'],
  'user-lock': ['draw', 'default', 'reveal'],
  'user-minus': ['draw', 'default', 'reveal'],
  'user-pen': ['draw', 'default', 'reveal'],
  'user-plus': ['draw', 'default', 'reveal'],
  'user-round': ['draw', 'default', 'alert', 'reveal'],
  'user-round-arrow-left': ['draw', 'default', 'reveal'],
  'user-round-check': ['draw', 'default', 'mark', 'reveal'],
  'user-round-cog': ['draw', 'default', 'active', 'reveal'],
  'user-round-key': ['draw', 'default', 'reveal'],
  'user-round-minus': ['draw', 'default', 'reveal'],
  'user-round-pen': ['draw', 'default', 'nudge', 'reveal'],
  'user-round-plus': ['draw', 'default', 'reveal'],
  'user-round-search': ['draw', 'default', 'reveal'],
  'user-round-x': ['draw', 'default', 'reveal'],
  'user-search': ['draw', 'default', 'reveal'],
  'user-shield': ['draw', 'default', 'reveal'],
  'user-star': ['draw', 'default', 'reveal'],
  'user-x': ['draw', 'default', 'reveal'],
  users: ['draw', 'default', 'reveal'],
  'users-round': ['draw', 'default', 'reveal'],
  utensils: ['draw', 'default', 'hold', 'reveal'],
  'utensils-crossed': ['draw', 'default', 'hold', 'reveal'],
  'utility-pole': ['draw', 'default', 'hold', 'reveal'],
  van: ['draw', 'default', 'hold', 'reveal'],
  variable: ['draw', 'default', 'reveal'],
  vault: ['draw', 'default', 'hold', 'reveal'],
  'vector-square': ['draw', 'default', 'hold', 'reveal'],
  vegan: ['draw', 'default', 'hold', 'reveal'],
  'venetian-mask': ['draw', 'default', 'hold', 'reveal'],
  venus: ['draw', 'default', 'hold', 'reveal'],
  'venus-and-mars': ['draw', 'default', 'hold', 'reveal'],
  vibrate: ['draw', 'default', 'reveal'],
  'vibrate-off': ['draw', 'default', 'strike', 'reveal'],
  video: ['draw', 'default', 'reveal'],
  'video-off': ['draw', 'default', 'strike', 'reveal'],
  videotape: ['draw', 'default', 'hold', 'reveal'],
  view: ['draw', 'default', 'hold', 'reveal'],
  voicemail: ['draw', 'default', 'hold', 'reveal'],
  volleyball: ['draw', 'default', 'hold', 'reveal'],
  volume: ['draw', 'default', 'reveal'],
  'volume-1': ['draw', 'default', 'reveal'],
  'volume-2': ['draw', 'default', 'spark', 'reveal'],
  'volume-off': ['draw', 'default', 'alert', 'strike', 'reveal'],
  'volume-x': ['draw', 'default', 'reveal'],
  vote: ['draw', 'default', 'reveal'],
  wallet: ['draw', 'default', 'hold', 'reveal'],
  'wallet-cards': ['draw', 'default', 'hold', 'reveal'],
  'wallet-minimal': ['draw', 'default', 'hold', 'reveal'],
  wallpaper: ['draw', 'default', 'hold', 'reveal'],
  wand: ['draw', 'default', 'hold', 'reveal'],
  'wand-sparkles': ['draw', 'default', 'hold', 'reveal'],
  warehouse: ['draw', 'default', 'reveal'],
  'washing-machine': ['draw', 'default', 'hold', 'reveal'],
  watch: ['draw', 'default', 'hold', 'reveal'],
  'waves-arrow-down': ['draw', 'default', 'hold', 'reveal'],
  'waves-arrow-up': ['draw', 'default', 'hold', 'reveal'],
  'waves-horizontal': ['draw', 'default', 'hold', 'reveal'],
  'waves-ladder': ['draw', 'default', 'hold', 'reveal'],
  'waves-vertical': ['draw', 'default', 'hold', 'reveal'],
  waypoints: ['draw', 'default', 'hold', 'reveal'],
  webcam: ['draw', 'default', 'reveal'],
  'webcam-off': ['draw', 'default', 'alert', 'strike', 'reveal'],
  webhook: ['draw', 'default', 'reveal'],
  'webhook-off': ['draw', 'default', 'strike', 'reveal'],
  weight: ['draw', 'default', 'hold', 'reveal'],
  'weight-tilde': ['draw', 'default', 'hold', 'reveal'],
  wheat: ['draw', 'default', 'reveal'],
  'wheat-off': ['draw', 'default', 'strike', 'reveal'],
  'whole-word': ['draw', 'default', 'reveal'],
  wifi: ['draw', 'default', 'cascade', 'reveal'],
  'wifi-cog': ['draw', 'default', 'reveal'],
  'wifi-high': ['draw', 'default', 'cascade', 'reveal'],
  'wifi-low': ['draw', 'default', 'cascade', 'reveal'],
  'wifi-off': ['draw', 'default', 'strike', 'reveal'],
  'wifi-pen': ['draw', 'default', 'reveal'],
  'wifi-sync': ['draw', 'default', 'reveal'],
  'wifi-zero': ['draw', 'default', 'cascade', 'reveal'],
  wind: ['draw', 'default', 'hold', 'reveal'],
  'wind-arrow-down': ['draw', 'default', 'hold', 'reveal'],
  wine: ['draw', 'default', 'reveal'],
  'wine-off': ['draw', 'default', 'strike', 'reveal'],
  workflow: ['draw', 'default', 'reveal'],
  worm: ['draw', 'default', 'hold', 'reveal'],
  wrench: ['draw', 'default', 'reveal'],
  'wrench-off': ['draw', 'default', 'alert', 'strike', 'reveal'],
  x: ['draw', 'default', 'reveal'],
  'x-line-top': ['draw', 'default', 'reveal'],
  zap: ['draw', 'default', 'spark', 'reveal'],
  'zap-off': ['draw', 'default', 'strike', 'reveal'],
  'zodiac-aquarius': ['draw', 'default', 'hold', 'reveal'],
  'zodiac-aries': ['draw', 'default', 'hold', 'reveal'],
  'zodiac-cancer': ['draw', 'default', 'hold', 'reveal'],
  'zodiac-capricorn': ['draw', 'default', 'hold', 'reveal'],
  'zodiac-gemini': ['draw', 'default', 'hold', 'reveal'],
  'zodiac-leo': ['draw', 'default', 'hold', 'reveal'],
  'zodiac-libra': ['draw', 'default', 'hold', 'reveal'],
  'zodiac-ophiuchus': ['draw', 'default', 'hold', 'reveal'],
  'zodiac-pisces': ['draw', 'default', 'hold', 'reveal'],
  'zodiac-sagittarius': ['draw', 'default', 'hold', 'reveal'],
  'zodiac-scorpio': ['draw', 'default', 'hold', 'reveal'],
  'zodiac-taurus': ['draw', 'default', 'hold', 'reveal'],
  'zodiac-virgo': ['draw', 'default', 'hold', 'reveal'],
  'zoom-in': ['draw', 'default', 'reveal'],
  'zoom-out': ['draw', 'default', 'reveal'],
};
